
export type Article = {
  slug: string;
  title: string;
  description: string;
  excerpt: string;
  category: string;
  publishedAt: string;
  updatedAt?: string;
  readTime: string;
  keywords: string[];
  /**
   * Article body. Plain strings render as paragraphs; strings prefixed with
   * "## " render as section headings; strings prefixed with "- " render as
   * bullet-list items (consecutive items are grouped into one list).
   */
  content: string[];
};

const seedArticles: Article[] = [
  {
    slug: "signs-your-child-may-benefit-from-occupational-therapy",
    title: "7 Signs Your Child May Benefit from Occupational Therapy",
    description:
      "Learn seven common signs that your child may benefit from a paediatric occupational therapy assessment — from sensory sensitivities to handwriting challenges.",
    excerpt:
      "When difficulties begin to affect play, learning, self-care, or social participation, an occupational therapy assessment may be beneficial. Here are seven signs to look for.",
    category: "Parent Guidance",
    publishedAt: "2025-11-15",
    readTime: "5 min",
    keywords: ["occupational therapy signs", "when to seek OT", "pediatric OT assessment"],
    content: [
      "Every child develops at their own pace, and occasional challenges are a normal part of growing up. However, when difficulties begin to affect everyday activities such as play, learning, self-care, or social participation, an occupational therapy assessment may be beneficial.",
      "Paediatric occupational therapy helps children develop the skills they need to participate confidently in daily life. Here are seven common signs that your child may benefit from professional support.",
      "## 1. Sensory Sensitivities",
      "Your child may become overwhelmed by loud sounds, bright lights, clothing textures, or certain foods, or constantly seek movement and sensory input. These behaviours may be associated with sensory processing differences that affect everyday functioning.",
      "## 2. Motor Skill Difficulties",
      "Difficulty with activities such as running, jumping, catching a ball, using scissors, colouring, or manipulating small objects may indicate challenges with coordination, balance, or motor planning.",
      "## 3. Persistent Handwriting Challenges",
      "If handwriting remains slow, illegible, or tiring despite regular practice, your child may have underlying difficulties with fine motor skills, visual-motor integration, or hand strength.",
      "## 4. Delays in Self-Care Skills",
      "Children who struggle with dressing, buttoning clothes, using cutlery, brushing their teeth, or other age-appropriate daily tasks may benefit from occupational therapy to build greater independence.",
      "## 5. Difficulty Maintaining Attention",
      "If your child finds it hard to stay engaged during schoolwork, play, or daily routines, the underlying cause may extend beyond attention alone. Occupational therapists assess how sensory, motor, and environmental factors influence participation.",
      "## 6. Frequent Emotional Dysregulation",
      "Regular meltdowns, frustration during transitions, or becoming easily overwhelmed by everyday situations may indicate difficulties with sensory or emotional regulation that can be addressed through therapy.",
      "## 7. Avoidance of Play or School Activities",
      "If your child avoids playground activities, art projects, handwriting, sports, or interacting with peers because these tasks seem difficult or frustrating, it may be a sign that additional support is needed.",
      "## When Should You Seek Help?",
      "Every child is unique, but if these challenges are persistent or interfere with your child's daily life at home, school, or in the community, an occupational therapy assessment can provide valuable insights. Early identification and intervention can help children build confidence, improve independence, and participate more successfully in meaningful everyday activities.",
      "Disclaimer: This article is intended for educational purposes only and should not be considered a substitute for professional assessment or medical advice. If you have concerns about your child's development, consult a qualified paediatric occupational therapist or healthcare professional.",
    ],
  },
  {
    slug: "preparing-your-child-for-first-occupational-therapy-appointment",
    title: "Preparing Your Child for Their First Occupational Therapy Appointment",
    description:
      "Practical guidance for parents on preparing a child for their first occupational therapy visit — what to bring, what to expect, and how to talk about it positively.",
    excerpt:
      "Your child's first OT appointment is an important step. Knowing what to expect can help everyone feel more comfortable and confident.",
    category: "Parent Guidance",
    publishedAt: "2026-01-05",
    readTime: "4 min",
    keywords: ["first OT appointment", "prepare child therapy visit", "occupational therapy first session"],
    content: [
      "Your child's first occupational therapy (OT) appointment is an important step toward understanding their strengths and supporting their development. It's natural for both children and parents to feel a little uncertain but knowing what to expect can help everyone feel more comfortable and confident.",
      "## Before the Appointment",
      "Talk to your child about the visit in a positive and reassuring way. Explain that they will meet a friendly therapist, play games, and try different activities. Avoid describing the appointment as a test or suggesting that something is \"wrong.\"",
      "A simple explanation such as, \"We're going to meet someone who helps children learn and play in fun ways,\" is often enough.",
      "Bring any previous medical or therapy reports, school feedback, referral letters, and a list of any questions or concerns you'd like to discuss. If your child has a favourite toy, blanket, or comfort item, feel free to bring it along.",
      "## What to Expect During the First Visit",
      "The first appointment usually begins with a discussion about your child's developmental history, daily routines, strengths, and the concerns that brought you to occupational therapy. The therapist will then observe your child through play-based activities and age-appropriate tasks to understand how they move, learn, interact, and participate in everyday activities.",
      "Depending on your child's needs, the therapist may recommend a comprehensive assessment, therapy sessions, or simple strategies to support your child at home.",
      "## After the Appointment",
      "Remember, occupational therapy is a collaborative process involving the child, family, and therapist. Working together helps create meaningful progress and supports your child's participation in everyday life.",
      "Consistency between therapy sessions and everyday routines plays an important role in helping children develop new skills.",
      "If you have concerns about your child's development or would like to schedule an occupational therapy assessment, we're here to support you every step of the way.",
    ],
  },
  {
    slug: "why-early-intervention-matters",
    title: "Why Early Intervention Matters for Your Child's Development",
    description:
      "Why seeking support early makes a meaningful difference — how neuroplasticity, parent involvement, and timely assessment help children reach their full potential.",
    excerpt:
      "Early intervention is not about labelling a child — it is about providing the right support at the right time to help them reach their full potential.",
    category: "Child Development",
    publishedAt: "2026-01-20",
    readTime: "5 min",
    keywords: ["early intervention", "child development support", "neuroplasticity early childhood"],
    content: [
      "Every child develops at their own pace, but when concerns about movement, communication, learning, behaviour, play, self-care, or sensory processing begin to affect everyday life, seeking support early can make a meaningful difference. Early intervention is not about labelling a child—it is about providing the right support at the right time to help them reach their full potential.",
      "The early years of life are a period of rapid brain development. During this time, the brain is highly adaptable, a quality known as neuroplasticity. New experiences and targeted interventions help strengthen the neural pathways that support learning, movement, communication, emotional regulation, and independence. Because of this, children often respond more effectively to therapy when intervention begins early.",
      "Parents play an essential role in the intervention process. Simple strategies incorporated into everyday routines, combined with therapy when needed, provide children with frequent opportunities to practice new skills in meaningful environments. Regular monitoring also ensures that intervention continues to meet the child's changing needs as they grow.",
      "One of the most common misconceptions is that families should \"wait and see\" if a child catches up. While some children naturally reach milestones later than others, persistent concerns should not be ignored. Seeking an assessment early provides valuable information, offers reassurance when development is progressing typically, and ensures that support can begin promptly when needed.",
      "Early intervention is not about rushing development—it is about giving children the best opportunity to build confidence, develop essential life skills, and participate fully in the activities that matter most. When concerns arise, seeking professional guidance early is one of the most positive steps a family can take to support a child's future.",
      "Disclaimer: This article is intended for educational purposes only and should not replace professional assessment or medical advice. If you have concerns about your child's development, consult a qualified healthcare professional for an appropriate evaluation.",
    ],
  },
  {
    slug: "picky-eating-or-sensory-challenge",
    title: "Is It Just Picky Eating or a Sensory Challenge?",
    description:
      "How to tell the difference between typical picky eating and a sensory-based feeding challenge — signs to watch for, home strategies, and how occupational therapy helps.",
    excerpt:
      "Nearly every child goes through a phase of being selective about food. But when eating becomes a daily struggle, it may be more than picky eating.",
    category: "Feeding & Nutrition",
    publishedAt: "2026-02-10",
    readTime: "7 min",
    keywords: ["picky eating children", "sensory feeding challenges", "feeding therapy"],
    content: [
      "\"My child only eats white foods.\" \"She gags whenever she tries something new.\" \"He refuses vegetables but happily eats chips.\"",
      "These are concerns many parents share. Nearly every child goes through a phase of being selective about food, but when eating becomes a daily struggle, families often wonder whether it is simply picky eating or something more.",
      "The answer is not always straightforward. While picky eating is common during childhood, some children avoid foods because their brains process sensory information differently. Understanding the difference is the first step toward helping your child develop a healthy relationship with food.",
      "## What Is Typical Picky Eating?",
      "Most young children become selective eaters at some stage of development. As children grow and become more independent, they naturally begin expressing preferences for certain foods while rejecting others.",
      "A child who is a typical picky eater may:",
      "- Prefer familiar foods.",
      "- Be hesitant to try new foods.",
      "- Change food preferences from week to week.",
      "- Eventually accept new foods after repeated exposure.",
      "- Continue to grow and meet nutritional needs.",
      "Although mealtimes may be frustrating, these children are generally able to tolerate different textures, smells, and appearances over time.",
      "## When Food Becomes More Than a Preference",
      "For some children, eating is not simply about likes and dislikes. It is about how their nervous system responds to sensory experiences.",
      "Every bite of food provides sensory information—texture, temperature, taste, smell, colour, and even sound. While most children process this information effortlessly, others may find certain sensations overwhelming or uncomfortable.",
      "A child with sensory processing differences may genuinely experience certain foods as unpleasant, confusing, or even distressing. Their refusal is often a protective response rather than an attempt to be difficult.",
      "## Signs That May Suggest a Sensory-Based Feeding Challenge",
      "Your child may benefit from further evaluation if they consistently:",
      "- Eats an extremely limited variety of foods.",
      "- Avoids entire food groups or textures.",
      "- Gags or vomits when trying certain foods.",
      "- Refuses foods based on their smell, colour, or appearance.",
      "- Becomes anxious or upset when new foods are offered.",
      "- Has difficulty sitting through family meals.",
      "- Prefers foods that are all crunchy, smooth, soft, or of a particular temperature.",
      "- Shows similar sensitivities to clothing, sounds, or other sensory experiences.",
      "One or two of these behaviours do not necessarily indicate a sensory challenge, but persistent patterns that interfere with nutrition or family life deserve attention.",
      "## Why Do Sensory Challenges Affect Eating?",
      "Eating is one of the most complex activities children learn. It requires the brain to integrate information from multiple sensory systems while coordinating movement, attention, and emotional regulation.",
      "If a child finds certain sensations overwhelming, they may avoid foods that feel sticky, crunchy, mixed, lumpy, or strongly flavoured. Others actively seek intense flavours or crunchy textures because these provide sensory input that feels more comfortable.",
      "Recognising these differences helps parents respond with understanding rather than frustration.",
      "## How Can Parents Help at Home?",
      "Supporting a child with feeding challenges begins with creating a positive mealtime experience. Some helpful strategies include:",
      "- Keep mealtimes calm and predictable.",
      "- Offer new foods alongside familiar favourites.",
      "- Allow your child to explore food by touching, smelling, or looking before expecting them to taste it.",
      "- Avoid forcing, bribing, or pressuring your child to eat.",
      "- Celebrate small steps, such as interacting with a new food, even if it is not eaten.",
      "- Remember that repeated, pressure-free exposure often increases acceptance over time.",
      "Building confidence around food is usually more effective than focusing on the number of bites a child takes.",
      "## How Occupational Therapy Can Help",
      "Occupational therapists evaluate how sensory processing, oral-motor skills, posture, attention, and daily routines influence a child's eating habits. By identifying the underlying reasons for food refusal, therapy can provide individualized strategies that support comfortable and enjoyable mealtimes.",
      "Intervention focuses on helping children gradually tolerate new sensory experiences, develop positive eating routines, and participate more confidently in family meals. Parents are actively involved throughout the process so that strategies can be successfully incorporated into everyday life.",
      "## When Should You Seek Professional Advice?",
      "If your child's eating habits are becoming increasingly restricted, causing significant stress during meals, affecting growth or nutrition, or limiting participation in everyday family activities, it is worth seeking a professional assessment.",
      "Early support can help identify whether the challenge is developmental, sensory, oral-motor, behavioural, or influenced by multiple factors. More importantly, it provides families with practical strategies tailored to their child's individual needs.",
      "Every child develops food preferences, but eating should not become a source of fear or constant conflict. Understanding the reason behind your child's eating behaviours is the first step toward making mealtimes more positive, enjoyable, and successful for the whole family.",
      "Disclaimer: This article is intended for educational purposes only and should not replace professional assessment or medical advice. If you have concerns about your child's feeding or development, consult a qualified healthcare professional or paediatric occupational therapist for an appropriate evaluation.",
    ],
  },
  {
    slug: "the-power-of-play",
    title: "The Power of Play: How Everyday Play Builds Your Child's Brain, Skills, and Confidence",
    description:
      "How everyday play builds brain development, motor skills, social communication, emotional resilience, and independence — and simple ways parents can encourage it.",
    excerpt:
      "Play is much more than fun — it is one of the most important ways children learn and develop the skills they need for everyday life.",
    category: "Child Development",
    publishedAt: "2026-02-15",
    readTime: "5 min",
    keywords: ["power of play child development", "play-based learning", "play skills children"],
    content: [
      "Play is much more than a way for children to have fun—it is one of the most important ways they learn and develop. Through play, children explore their environment, solve problems, build relationships, and develop the physical, cognitive, social, and emotional skills they need for everyday life.",
      "During the early years, the brain develops rapidly, and every meaningful play experience helps strengthen the neural connections that support learning, communication, movement, and independence. Whether a child is building with blocks, climbing at the playground, pretending to cook, or drawing a picture, they are developing skills that will support them throughout childhood and beyond.",
      "## Brain Development and Learning",
      "Play encourages curiosity, creativity, and problem-solving. As children experiment, make decisions, and explore new ideas, they develop attention, memory, planning, and flexible thinking—skills that are essential for success in school and everyday life.",
      "## Motor Skills",
      "Activities such as running, jumping, climbing, throwing, colouring, and building strengthen both gross and fine motor skills. These experiences improve balance, coordination, hand strength, body awareness, and visual-motor integration, all of which contribute to greater independence in daily activities.",
      "## Social and Communication Skills",
      "Playing with siblings, friends, or caregivers helps children learn important social skills such as sharing, taking turns, listening, negotiating, and working together. Pretend play also supports language development, imagination, and understanding of different perspectives.",
      "## Emotional Development",
      "Play provides children with opportunities to express emotions, manage frustration, build confidence, and develop resilience. Learning to cope when a tower falls or when a game doesn't go as planned teaches valuable emotional regulation skills.",
      "## Independence and Everyday Life Skills",
      "Simple activities such as dressing dolls, setting up pretend kitchens, helping with household tasks, or completing puzzles encourage planning, organisation, responsibility, and confidence in everyday routines.",
      "## Simple Ways to Encourage Meaningful Play",
      "Parents do not need expensive toys or structured activities to support development. Some of the most valuable learning happens through everyday experiences. You can encourage meaningful play by:",
      "- Allowing time for free, unstructured play each day.",
      "- Spending time outdoors exploring nature and playgrounds.",
      "- Reading stories and encouraging imaginative play.",
      "- Providing open-ended materials such as blocks, crayons, puzzles, or clay.",
      "- Limiting unnecessary screen time and encouraging active play.",
      "The goal is not to keep children constantly entertained but to give them opportunities to explore, create, and learn through experience.",
      "## When Should Parents Be Concerned?",
      "While every child develops differently, some children may avoid play, become easily frustrated during activities, struggle to interact with peers, or have difficulty participating in age-appropriate games. These challenges may be related to motor skills, sensory processing, attention, or emotional regulation.",
      "If play consistently becomes difficult or your child is unable to participate in everyday activities with confidence, an occupational therapy assessment can help identify underlying challenges and provide strategies to support development.",
      "Play is not a break from learning—it is one of the most powerful ways children learn. Every game, every adventure, and every moment of exploration helps build the skills needed for school, relationships, independence, and lifelong learning.",
      "By encouraging meaningful play every day, parents are giving their children one of the greatest gifts for healthy development.",
      "Disclaimer: This article is intended for educational purposes only and should not replace professional assessment or medical advice. If you have concerns about your child's development, consult a qualified pediatric occupational therapist or healthcare professional.",
    ],
  },
  {
    slug: "everyday-moments-lifelong-skills",
    title: "Everyday Moments, Lifelong Skills: Simple Daily Activities That Help Children Learn and Thrive",
    description:
      "How ordinary daily routines — cooking, laundry, outdoor play, conversation — build motor skills, problem-solving, confidence, and independence in children.",
    excerpt:
      "Some of the most valuable learning happens during ordinary moments at home. Daily routines are full of opportunities for children to learn and thrive.",
    category: "Parent Guidance",
    publishedAt: "2026-03-01",
    readTime: "5 min",
    keywords: ["daily activities child development", "learning through routines", "independence skills children"],
    content: [
      "Many parents believe that children learn best through structured lessons, educational toys, or organised activities. While these certainly have their place, some of the most valuable learning happens during ordinary moments at home.",
      "Daily routines provide countless opportunities for children to develop motor skills, problem-solving abilities, communication, confidence, and independence. With a little encouragement, everyday activities can become meaningful learning experiences that support healthy development without feeling like extra work.",
      "## Why Everyday Activities Matter",
      "Children learn best by doing. Every time they help, explore, experiment, or solve a small problem, they are strengthening the skills needed for school, friendships, and everyday life.",
      "Unlike structured teaching, everyday activities are meaningful because children can immediately see the purpose of what they are doing. This makes learning more natural, enjoyable, and easier to remember.",
      "## Helping in the Kitchen",
      "Simple cooking activities encourage children to measure, pour, stir, peel, and mix. These tasks help develop hand strength, bilateral coordination, sequencing, attention, and early mathematical concepts. They also promote responsibility and confidence.",
      "## Setting the Table",
      "Placing plates, spoons, and cups in the correct positions develops visual perception, planning, spatial awareness, and organisational skills. It also encourages children to follow routines and contribute to family life.",
      "## Folding Laundry",
      "Sorting clothes by colour or size, matching socks, and folding towels strengthen visual discrimination, problem-solving, bilateral coordination, and fine motor skills. These activities also teach responsibility and independence.",
      "## Drawing, Colouring, and Craft Activities",
      "Creative activities improve pencil control, hand strength, hand-eye coordination, and visual-motor integration while encouraging imagination and self-expression. These skills form an important foundation for handwriting and classroom learning.",
      "## Outdoor Play",
      "Running, climbing, jumping, cycling, and playing ball games help children develop balance, coordination, strength, endurance, and body awareness. Outdoor play also supports confidence, social interaction, and emotional well-being.",
      "## Building with Blocks and Puzzles",
      "Construction toys and puzzles encourage planning, problem-solving, creativity, visual-spatial skills, and sustained attention. Children also learn persistence as they work through challenges and celebrate success.",
      "## Encouraging Independence",
      "Children often learn best when they are trusted to do things for themselves.",
      "Allowing your child to dress independently, pack their school bag, water plants, organise toys, or help with simple household tasks teaches far more than practical skills. These experiences develop planning, decision-making, confidence, and a sense of responsibility.",
      "Although these tasks may take longer at first, giving children opportunities to participate independently helps them become more capable over time.",
      "## Learning Through Conversation",
      "Development is supported not only through activities but also through everyday conversations.",
      "Talk with your child while shopping, cooking, travelling, or walking together. Ask open-ended questions, encourage them to describe what they see, solve simple problems, and share their ideas. These interactions strengthen language, thinking skills, memory, and social communication.",
      "## Small Moments Create Big Opportunities",
      "Children do not need every minute of their day to be carefully planned. In fact, unhurried family routines often provide the richest learning experiences.",
      "Reading a bedtime story, gardening together, baking a cake, organising toys, or simply taking a walk around the neighbourhood all encourage curiosity, communication, creativity, and confidence.",
      "The goal is not to create more work for parents but to recognise the learning opportunities already present in everyday life.",
      "## When Everyday Activities Become Challenging",
      "Some children may avoid age-appropriate activities, become easily frustrated, or require significant help with tasks that their peers manage independently. Difficulties with attention, coordination, sensory processing, or motor skills can make everyday routines more challenging.",
      "If these difficulties consistently affect your child's participation at home, school, or in the community, a professional assessment can help identify the underlying reasons and provide practical strategies to support development.",
      "Children do not learn only in classrooms or therapy sessions—they learn through everyday experiences shared with the people who matter most. Every meal prepared together, every puzzle completed, every story read, and every household task accomplished contributes to a child's growth and independence.",
      "By involving children in daily routines and encouraging active participation, parents can help build the skills that support lifelong learning, confidence, and success.",
      "Disclaimer: This article is intended for educational purposes only and should not replace professional assessment or medical advice. If you have concerns about your child's development, consult a qualified paediatric occupational therapist or healthcare professional.",
    ],
  },
  {
    slug: "screen-time-and-your-childs-developing-brain",
    title: "How Excessive Screen Time Can Affect Your Child's Developing Brain",
    description:
      "How excessive screen time influences attention, emotional regulation, sleep, and social development in children — and how families can find a healthy balance.",
    excerpt:
      "During the early years — when the brain is developing rapidly — the quality and amount of screen exposure matter. Here's what parents should know.",
    category: "Child Development",
    publishedAt: "2026-03-10",
    readTime: "5 min",
    keywords: ["screen time children", "child brain development screens", "healthy screen habits"],
    content: [
      "Screens have become a natural part of modern childhood. They help us learn, communicate, and entertain ourselves. However, during the early years—when the brain is developing rapidly—the quality and amount of screen exposure matter.",
      "The developing brain is shaped by everyday experiences. While age-appropriate digital media can have a place in a child's routine, excessive screen time may influence how children pay attention, regulate emotions, interact with others, and engage with the world around them.",
      "## 1. Screens Influence the Brain's Reward System",
      "Many digital games, videos, and apps are designed to provide instant rewards through bright visuals, rapid scene changes, and continuous novelty. This repeated stimulation activates the brain's reward pathways, making fast-paced digital experiences highly engaging.",
      "Over time, some children may find slower activities that require patience, persistence, or sustained effort less motivating.",
      "## 2. Healthy Attention Is Built, Not Captured",
      "Capturing a child's attention is different from developing it.",
      "Real-life learning requires children to focus, ignore distractions, shift attention when needed, and stay engaged even when an activity is challenging. Excessive exposure to constantly changing digital content may reduce opportunities to practise these important attention skills.",
      "## 3. Emotional Regulation Develops Through Everyday Experiences",
      "Children gradually learn to manage frustration, boredom, waiting, and disappointment through everyday life. These experiences help build resilience and self-regulation.",
      "When screens become the primary way to calm, distract, or occupy a child, they may have fewer opportunities to develop healthy coping strategies for managing emotions independently.",
      "## 4. Sleep Supports Brain Development",
      "A well-rested brain learns more effectively.",
      "Quality sleep helps consolidate memories, supports emotional regulation, and strengthens learning. Screen use close to bedtime may interfere with healthy sleep routines in some children, making it harder to fall asleep or achieve restorative sleep.",
      "## 5. Human Interaction Builds the Social Brain",
      "Children learn communication by interacting with people, not just by watching them.",
      "Every conversation, shared smile, eye contact, facial expression, and back-and-forth interaction strengthens the brain networks responsible for language, empathy, social understanding, and emotional connection. These experiences are difficult to replicate through screens alone.",
      "## 6. The Brain Needs Time to Think",
      "Not every moment needs to be filled with entertainment.",
      "Quiet moments encourage children to observe, imagine, solve problems, ask questions, and create their own ideas. These experiences strengthen creativity, flexible thinking, and independent problem-solving—skills that are essential for lifelong learning.",
      "## Finding the Right Balance",
      "Technology is not the enemy, nor does every minute of screen time harm a child's development. The goal is to use screens intentionally while ensuring they do not replace the experiences that are most important during childhood. Parents can support healthy brain development by:",
      "- Creating screen-free family routines, especially during meals and before bedtime.",
      "- Choosing age-appropriate, high-quality digital content.",
      "- Watching or engaging with content together whenever possible.",
      "- Encouraging regular conversations, reading, outdoor play, creative activities, and meaningful family interactions.",
      "- Modelling healthy screen habits through their own behaviour.",
      "The developing brain is shaped by repeated experiences. Screens are one part of a child's world, but they should never replace the relationships, conversations, movement, creativity, curiosity, and everyday experiences that help children grow into confident, capable, and independent individuals.",
      "Rather than asking, \"How much screen time is too much?\", a more meaningful question is: \"Is my child's day filled with enough real-life experiences to support healthy brain development?\"",
      "When balance is the goal, technology can remain a useful tool while childhood continues to be rich in learning, connection, and discovery.",
      "Disclaimer: This article is intended for educational purposes only and should not replace professional assessment or medical advice. If you have concerns about your child's development, behaviour, attention, or screen use, consult a qualified healthcare professional or paediatric occupational therapist.",
    ],
  },
];

export const articles: Article[] = [...seedArticles];

export function getArticle(slug: string) {
  return articles.find((a) => a.slug === slug);
}

export const articleCategories = [...new Set(articles.map((a) => a.category))];
