import type { ConditionContent } from "@/lib/conditions-content";

export const additionalConditionsContent: ConditionContent[] = [
  {
    slug: "primitive-reflex-retention",
    title: "Primitive Reflex Retention",
    metaDescription: "RMTI & MNRI reflex integration therapy in Mumbai. Dr. Sharuja Sarap helps children integrate retained primitive reflexes in Kandivali.",
    keywords: ["primitive reflex therapy Mumbai", "reflex integration Kandivali", "RMTI MNRI Mumbai"],
    intro: "Primitive reflexes are automatic movement patterns present in infancy that should integrate as the brain matures. When these reflexes remain active beyond expected ages, they can affect posture, coordination, attention, reading readiness, and emotional regulation. At Thrive with sharuja, Dr. Sharuja Sarap uses RMTI and MNRI reflex integration approaches to help children in Kandivali West build stronger nervous system foundations.",
    symptoms: [
      "Poor posture — slumping, W-sitting, or head lag",
      "Difficulty with midline crossing and bilateral coordination",
      "Retained Moro, ATNR, or STNR reflex patterns",
      "Clumsiness and difficulty learning new motor skills",
      "Reading difficulties linked to eye tracking or coordination",
      "Emotional reactivity and poor stress tolerance",
      "Difficulty with balance and core stability",
      "Attention challenges that persist despite other interventions",
    ],
    challenges: [
      "Academic struggles despite adequate intelligence",
      "Persistent coordination difficulties not resolving with practice",
      "Emotional dysregulation disproportionate to situations",
      "Poor sitting posture affecting classroom tolerance",
      "Difficulty with sports and physical play",
      "Frustration from repeated failed attempts at new skills",
      "Parents unsure why progress in other therapies is slow",
    ],
    therapyRole: [
      "Comprehensive reflex and movement pattern assessment",
      "RMTI rhythmic movement protocols for reflex integration",
      "MNRI neurosensorimotor reflex integration techniques",
      "Postural stability and core strengthening activities",
      "Home reflex integration programs with parent guidance",
      "Integration with OT sensory and motor goals",
      "Progress monitoring through functional skill changes",
      "Coordination with academic and school support strategies",
    ],
    benefits: [
      "Improved postural control and motor coordination",
      "Better attention and learning readiness",
      "Reduced emotional reactivity and improved regulation",
      "Foundation for reading, writing, and classroom success",
      "Greater confidence in physical activities",
      "Parents understand the neurological basis of challenges",
      "Measurable progress in foundational skills over time",
    ],
    whenToBegin: "If your child shows persistent coordination, attention, or postural challenges that have not responded to conventional approaches, a reflex integration assessment can identify whether retained reflexes are contributing.",
    faqs: [
      { q: "Can retained reflexes be integrated at older ages?", a: "Yes. The nervous system remains adaptable. Reflex integration therapy can benefit children at any age up to 14 years." },
      { q: "How long does reflex integration take?", a: "Most families see foundational changes within 8–16 weeks of consistent practice, with ongoing progress over months." },
      { q: "Is reflex integration evidence-based?", a: "Reflex integration is widely used in pediatric OT internationally. Dr. Sharuja Sarap integrates RMTI and MNRI within her evidence-informed framework." },
    ],
    relatedServices: ["rmti", "mnri", "occupational-therapy", "brain-gym"],
  },
  {
    slug: "emotional-regulation-difficulties",
    title: "Emotional Regulation Difficulties",
    metaDescription: "OT for emotional regulation in children Mumbai. Dr. Sharuja Sarap helps kids manage emotions through sensory-motor strategies in Kandivali.",
    keywords: ["emotional regulation therapy Mumbai", "child emotional support Kandivali", "sensory regulation OT"],
    intro: "Emotional regulation difficulties affect a child's ability to manage feelings, recover from upsets, and respond appropriately to daily challenges. Often linked to sensory processing, motor planning, or nervous system immaturity, these challenges can disrupt family life, school participation, and social relationships. Dr. Sharuja Sarap at Thrive with sharuja provides compassionate, sensory-integrative occupational therapy that helps children build practical regulation skills.",
    symptoms: [
      "Intense emotional reactions disproportionate to triggers",
      "Difficulty calming down after upset or excitement",
      "Frequent meltdowns or emotional outbursts",
      "Low frustration tolerance during tasks",
      "Anxiety in new or unpredictable situations",
      "Mood swings affecting daily routines",
      "Difficulty identifying and expressing emotions",
      "Avoidance of challenging or unfamiliar activities",
    ],
    challenges: [
      "Family stress from unpredictable emotional episodes",
      "School behavior concerns and teacher feedback",
      "Social friction from emotional reactivity",
      "Difficulty completing tasks when frustrated",
      "Sleep disruption linked to emotional dysregulation",
      "Parent exhaustion from constant co-regulation demands",
      "Risk of low self-esteem from repeated emotional struggles",
    ],
    therapyRole: [
      "Sensory profile assessment to understand regulation triggers",
      "Sensory integration activities for nervous system calming",
      "Co-regulation strategies for parents and caregivers",
      "Movement-based regulation tools — Brain Gym, rhythmic movement",
      "Visual supports and routine structures for predictability",
      "Graded exposure to challenging emotional situations",
      "Self-awareness activities adapted to child's developmental level",
      "School collaboration for regulation-friendly environments",
    ],
    benefits: [
      "Reduced frequency and intensity of meltdowns",
      "Faster recovery from emotional upsets",
      "Practical regulation tools child can use independently",
      "Parents equipped with co-regulation strategies",
      "Improved tolerance of transitions and changes",
      "Better classroom behavior and participation",
      "Child develops emotional vocabulary and self-awareness",
    ],
    whenToBegin: "If emotional reactions are limiting your child's participation in daily life, school, or social activities, early OT support can prevent secondary issues like anxiety and social withdrawal.",
    faqs: [
      { q: "Is poor emotional regulation my fault as a parent?", a: "Never. Regulation difficulties often have sensory-neurological roots. Seeking support is one of the most loving decisions you can make." },
      { q: "Can OT help without medication?", a: "Many children benefit from OT-based regulation strategies. We collaborate with pediatricians when families explore combined approaches." },
      { q: "How do you teach regulation to young children?", a: "Through play, movement, sensory activities, and visual supports — never through punishment or pressure." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "rmti", "mnri"],
  },
  {
    slug: "school-readiness-concerns",
    title: "School Readiness Concerns",
    metaDescription: "School readiness OT in Mumbai & Kandivali. Dr. Sharuja Sarap prepares children for classroom success through pediatric occupational therapy.",
    keywords: ["school readiness therapy Mumbai", "pre-school OT Kandivali", "classroom readiness Mumbai"],
    intro: "School readiness encompasses far more than knowing letters and numbers — it requires pencil control, sitting tolerance, self-regulation, social skills, and the motor foundations for classroom participation. When children enter school without these foundations, frustration and disengagement often follow. Dr. Sharuja Sarap at Thrive with sharuja provides comprehensive school readiness support for families in Kandivali West and across Mumbai.",
    symptoms: [
      "Poor pencil grip and pre-writing skills for age",
      "Difficulty sitting still during table activities",
      "Limited attention during structured group activities",
      "Difficulty following classroom routines and instructions",
      "Social hesitation in group or peer settings",
      "Delayed self-care skills — opening lunch boxes, managing clothing",
      "Sensory intolerance of classroom environments",
      "Resistance to academic or structured tasks",
    ],
    challenges: [
      "Teacher concerns in the first weeks of school",
      "Child labeled as disruptive or inattentive early on",
      "Homework battles beginning in early primary years",
      "Social isolation from difficulty participating in group work",
      "Parent anxiety about child's academic trajectory",
      "Need for early accommodations and support plans",
      "Risk of negative school experiences affecting self-esteem",
    ],
    therapyRole: [
      "Comprehensive school readiness assessment",
      "Fine motor and handwriting preparation — HWT-based",
      "Sensory regulation strategies for classroom tolerance",
      "Attention and executive function skill building",
      "Social participation activities — turn-taking, group tasks",
      "Self-care skills training for school independence",
      "School visit recommendations and teacher collaboration",
      "Parent coaching on home routines supporting school success",
    ],
    benefits: [
      "Confident entry into formal schooling",
      "Functional pencil grip and pre-writing skills",
      "Improved sitting tolerance and attention",
      "Practical classroom accommodations in place",
      "Child approaches school with positive expectations",
      "Teachers equipped with supportive strategies",
      "Parents feel prepared and empowered",
    ],
    whenToBegin: "Six to twelve months before school entry is ideal, but children already struggling in early grades benefit significantly from targeted school readiness OT.",
    faqs: [
      { q: "What age should we start school readiness OT?", a: "From age 3–4 for pre-school preparation, or anytime concerns arise before or during early school years." },
      { q: "Does school readiness OT include academics?", a: "OT addresses the motor, sensory, and regulation foundations that make academic learning possible — complementing rather than replacing academics." },
      { q: "Can you provide reports for school admission?", a: "Yes. We provide assessment reports and recommendations upon request." },
    ],
    relatedServices: ["occupational-therapy", "handwriting-training", "brain-gym"],
  },
  {
    slug: "down-syndrome",
    title: "Down Syndrome",
    metaDescription: "Pediatric OT for Down syndrome in Mumbai. Dr. Sharuja Sarap supports motor, sensory & daily living skills in Kandivali West.",
    keywords: ["Down syndrome occupational therapy Mumbai", "OT Down syndrome Kandivali", "pediatric OT Down syndrome"],
    intro: "Children with Down syndrome benefit enormously from early, individualized occupational therapy that addresses low muscle tone, sensory processing, fine and gross motor development, and daily living independence. At Thrive with sharuja, Dr. Sharuja Sarap provides warm, strength-based pediatric OT that celebrates each child's unique abilities while building the skills for confident participation at home, school, and in the community.",
    symptoms: [
      "Low muscle tone (hypotonia) affecting posture and movement",
      "Delayed fine and gross motor milestones",
      "Difficulty with self-care — dressing, feeding, grooming",
      "Sensory processing differences — seeking or avoiding input",
      "Short attention span for structured tasks",
      "Oral-motor challenges affecting feeding and speech readiness",
      "Difficulty with tool use — scissors, pencils, utensils",
      "Social engagement challenges in group settings",
    ],
    challenges: [
      "Slower progress in motor milestones compared to peers",
      "Dependence on caregivers for daily living tasks",
      "School placement and accommodation navigation",
      "Feeding difficulties and selective eating",
      "Parent concern about long-term independence",
      "Need for coordinated multi-disciplinary care",
      "Social participation in age-appropriate activities",
    ],
    therapyRole: [
      "Comprehensive motor and sensory assessment",
      "Low-tone strengthening through play-based activities",
      "Fine motor skill development for self-care and classroom",
      "Sensory integration for regulation and engagement",
      "OPT-based feeding and oral-motor support when needed",
      "Aquatic therapy for strength and confidence in movement",
      "Adaptive equipment and technique recommendations",
      "Family coaching and school collaboration",
    ],
    benefits: [
      "Improved muscle tone and postural stability",
      "Greater independence in daily living skills",
      "Enhanced fine motor skills for school tasks",
      "Better sensory regulation and attention",
      "Increased participation in play and social activities",
      "Parents equipped with home programs and strategies",
      "Celebration of every functional milestone achieved",
    ],
    whenToBegin: "Early intervention from infancy through toddlerhood yields the best outcomes, but meaningful progress is possible at every age up to 14 years.",
    faqs: [
      { q: "How is OT different from physiotherapy for Down syndrome?", a: "Physiotherapy focuses on gross motor function. OT addresses participation in daily activities — self-care, play, school, and social life." },
      { q: "Can aquatic therapy help children with Down syndrome?", a: "Yes. Water supports low-tone muscles and provides a joyful environment for strength and coordination building." },
      { q: "Do you coordinate with other specialists?", a: "Yes. We collaborate with pediatricians, speech therapists, and educators for comprehensive care." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy", "opt", "handwriting-training"],
  },
  {
    slug: "feeding-oral-motor-challenges",
    title: "Feeding & Oral Motor Challenges",
    metaDescription: "OPT feeding therapy for children in Mumbai. Dr. Sharuja Sarap addresses picky eating, oral aversions & mealtime challenges in Kandivali.",
    keywords: ["feeding therapy Mumbai", "picky eating OT Kandivali", "oral motor therapy children Mumbai"],
    intro: "Feeding and oral-motor challenges affect a child's nutrition, growth, family mealtimes, and overall wellbeing. Whether caused by sensory aversions, oral-motor weakness, or developmental differences, these difficulties require specialized, patient intervention. Dr. Sharuja Sarap — certified in Oral Placement Therapy (OPT) — provides compassionate feeding support at Thrive with sharuja in Kandivali West.",
    symptoms: [
      "Extremely limited food variety — fewer than 10–15 foods",
      "Gagging or refusal with certain textures or temperatures",
      "Difficulty chewing or transitioning to solid foods",
      "Oral hypersensitivity — distress with tooth brushing or utensils",
      "Pocketing food or prolonged mealtimes",
      "Failure to thrive or inadequate nutrition from selective eating",
      "Mealtime battles causing family stress",
      "Difficulty with cup drinking or straw use",
    ],
    challenges: [
      "Parent anxiety about nutrition and growth",
      "Social exclusion from family and social mealtimes",
      "School lunch challenges and peer observations",
      "Exhaustion from daily mealtime battles",
      "Need for medical monitoring alongside therapy",
      "Difficulty finding practitioners with feeding expertise",
      "Impact on family relationships and daily routines",
    ],
    therapyRole: [
      "Comprehensive oral-motor and feeding assessment",
      "OPT exercises for oral strength and coordination",
      "Sensory desensitization for oral and food textures",
      "Graded food exposure in safe, playful context",
      "Mealtime routine and environmental modifications",
      "Parent coaching on responsive feeding approaches",
      "Coordination with pediatricians and dietitians",
      "Home practice programs for oral-motor skill building",
    ],
    benefits: [
      "Expanded food acceptance over time",
      "Reduced mealtime stress for the whole family",
      "Improved oral-motor skills for safe eating",
      "Better nutrition through gradual dietary expansion",
      "Parents equipped with practical feeding strategies",
      "Child experiences mealtimes more positively",
      "Foundation for speech articulation when applicable",
    ],
    whenToBegin: "If feeding difficulties are affecting nutrition, growth, or family wellbeing — or if oral aversions persist beyond typical developmental stages — specialized OT feeding support can help.",
    faqs: [
      { q: "Is picky eating the same as a feeding disorder?", a: "Picky eating exists on a spectrum. When it significantly limits nutrition or causes distress, professional assessment is recommended." },
      { q: "How is OPT used for feeding?", a: "OPT uses targeted exercises and tools to develop oral-motor skills needed for safe, enjoyable eating." },
      { q: "Will you force my child to eat new foods?", a: "Never. We use gradual, child-led exposure in a safe, playful therapeutic relationship." },
    ],
    relatedServices: ["opt", "occupational-therapy"],
  },
  {
    slug: "social-participation-challenges",
    title: "Social Participation Challenges",
    metaDescription: "OT for social participation in children Mumbai. Dr. Sharuja Sarap builds confidence for peer play & group activities in Kandivali.",
    keywords: ["social skills OT Mumbai", "peer play therapy Kandivali", "social participation children"],
    intro: "Social participation challenges affect a child's ability to engage with peers, join group activities, and build meaningful friendships. These difficulties often stem from underlying sensory, motor, attention, or regulation challenges rather than a lack of desire to connect. Dr. Sharuja Sarap at Thrive with sharuja helps children in Mumbai develop the foundational skills for confident social engagement.",
    symptoms: [
      "Preference for solitary play over peer interaction",
      "Difficulty with turn-taking and sharing",
      "Withdrawal from group activities and birthday parties",
      "Social friction from impulsive or unexpected behaviors",
      "Difficulty reading social cues and personal space",
      "Limited pretend play or cooperative play for age",
      "Anxiety in social or group settings",
      "Difficulty initiating or maintaining friendships",
    ],
    challenges: [
      "Social isolation and loneliness",
      "Bullying or exclusion from peer groups",
      "Parent concern about child's social development",
      "Difficulty participating in school group work",
      "Missed opportunities for social learning",
      "Low self-esteem from social rejection experiences",
      "Family limitation of social outings due to child's distress",
    ],
    therapyRole: [
      "Assessment of sensory, motor, and regulation factors affecting social engagement",
      "Structured social play activities in clinic setting",
      "Turn-taking, joint attention, and cooperative play skill building",
      "Sensory regulation strategies for social environments",
      "Role-play and guided practice for social scenarios",
      "Parent coaching on facilitating peer interactions",
      "School recommendations for social participation support",
      "Building confidence through success-based social experiences",
    ],
    benefits: [
      "Increased willingness to engage in peer play",
      "Improved turn-taking and cooperative play skills",
      "Greater confidence in group settings",
      "Practical strategies for managing social anxiety",
      "Parents equipped to support social opportunities",
      "Child experiences successful social interactions",
      "Foundation for lasting friendships over time",
    ],
    whenToBegin: "If your child consistently avoids peer interaction, struggles in group settings, or has difficulty making friends compared to peers, OT can address underlying barriers to social participation.",
    faqs: [
      { q: "Is social skills therapy the same as social skills groups?", a: "OT addresses the sensory-motor and regulation foundations that make social engagement possible, within individualized therapeutic sessions." },
      { q: "Can OT help shy children?", a: "Yes. We build regulation and confidence gradually, respecting each child's temperament while expanding their social comfort zone." },
      { q: "Does this help children with autism?", a: "Yes. Social participation support is a core component of OT for children with ASD and related profiles." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "rmti"],
  },
  {
    slug: "fine-motor-challenges",
    title: "Fine Motor Challenges",
    metaDescription: "Fine motor therapy for children in Mumbai. Dr. Sharuja Sarap develops hand skills, dexterity & tool use in Kandivali West.",
    keywords: ["fine motor therapy Mumbai", "hand skills OT Kandivali", "fine motor development children"],
    intro: "Fine motor challenges affect a child's ability to use their hands precisely for writing, cutting, buttoning, feeding, and countless daily tasks. When fine motor skills lag behind peers, children may avoid activities, fall behind academically, and lose confidence. Dr. Sharuja Sarap provides targeted fine motor occupational therapy at Thrive with sharuja in Kandivali West.",
    symptoms: [
      "Weak pencil grip and poor handwriting",
      "Difficulty using scissors, utensils, or tools",
      "Avoidance of fine motor activities — crafts, puzzles, building",
      "Difficulty with buttons, zippers, and shoe fasteners",
      "Hand fatigue during writing or drawing tasks",
      "Poor dexterity compared to age-matched peers",
      "Difficulty with precise finger movements",
      "Dropping objects frequently or clumsy hand use",
    ],
    challenges: [
      "Academic impact through poor written output",
      "Dependence on parents for dressing and self-care",
      "Avoidance of art, crafts, and classroom activities",
      "Low self-confidence about manual abilities",
      "Teacher concerns about classroom participation",
      "Difficulty with age-appropriate independence skills",
      "Frustration leading to task refusal",
    ],
    therapyRole: [
      "Comprehensive fine motor and hand function assessment",
      "Hand strengthening and dexterity activities through play",
      "Pencil grip correction and adaptive tool recommendations",
      "Handwriting Without Tears® intervention when writing is affected",
      "Self-care fine motor skill training — dressing, feeding, grooming",
      "Visual-motor integration activities",
      "Home practice programs with engaging activities",
      "School collaboration for classroom tool use and accommodations",
    ],
    benefits: [
      "Improved hand strength and dexterity",
      "Functional pencil grip and writing skills",
      "Greater independence in self-care tasks",
      "Increased willingness to engage in fine motor activities",
      "Classroom-ready tool use and written work",
      "Parents equipped with home strengthening activities",
      "Child builds confidence in manual abilities",
    ],
    whenToBegin: "If fine motor skills are clearly behind peers by age 4–5, or if writing and self-care tasks are causing daily frustration, targeted fine motor OT can make a significant difference.",
    faqs: [
      { q: "Will fine motor activities feel like homework?", a: "No. We use play-based, engaging activities that children enjoy — building skills through fun, not drills." },
      { q: "How is fine motor OT different from handwriting training?", a: "Fine motor OT addresses all hand skills. Handwriting training is a specialized subset when writing is the primary concern." },
      { q: "Can fine motor skills improve in older children?", a: "Yes. The brain remains adaptable. Older children often make rapid progress with targeted intervention." },
    ],
    relatedServices: ["handwriting-training", "occupational-therapy", "brain-gym"],
  },
  {
    slug: "gross-motor-difficulties",
    title: "Gross Motor Difficulties",
    metaDescription: "Gross motor therapy for children in Mumbai. Dr. Sharuja Sarap improves balance, strength & coordination in Kandivali through OT & aquatics.",
    keywords: ["gross motor therapy Mumbai", "balance coordination children Kandivali", "motor skills OT Mumbai"],
    intro: "Gross motor difficulties affect a child's ability to use large muscle groups for running, jumping, balancing, climbing, and participating in physical play. These challenges impact playground participation, sports, PE classes, and overall physical confidence. Dr. Sharuja Sarap at Thrive with sharuja provides gross motor occupational therapy and aquatic therapy for children across Mumbai.",
    symptoms: [
      "Delayed walking, running, or jumping for age",
      "Poor balance — frequent falling or unsteadiness",
      "Difficulty climbing stairs, playground equipment, or bikes",
      "Awkward running or jumping patterns",
      "Low endurance during physical activities",
      "Avoidance of PE, sports, and active play",
      "Difficulty with ball skills — catching, throwing, kicking",
      "Poor postural stability during seated tasks",
    ],
    challenges: [
      "Exclusion from physical play and sports",
      "Low physical fitness and sedentary preferences",
      "Social isolation from inability to keep up with peers",
      "Safety concerns during physical activities",
      "Impact on posture affecting fine motor and writing",
      "Parent worry about long-term physical development",
      "School PE difficulties and negative experiences",
    ],
    therapyRole: [
      "Gross motor and balance assessment",
      "Strength and endurance building through purposeful play",
      "Balance and postural stability training",
      "Motor planning activities for new physical skills",
      "Aquatic therapy for strength in reduced-gravity environment",
      "Ball skills and bilateral coordination activities",
      "Home exercise programs for daily practice",
      "School PE accommodations and participation strategies",
    ],
    benefits: [
      "Improved balance, strength, and coordination",
      "Greater participation in playground and sports",
      "Increased physical confidence and endurance",
      "Better postural stability supporting fine motor skills",
      "Reduced clumsiness-related injuries",
      "Foundation for lifelong physical activity enjoyment",
      "Child approaches physical challenges with confidence",
    ],
    whenToBegin: "If your child avoids physical play, falls frequently, or cannot keep up with peers in gross motor activities, early OT intervention builds skills and confidence before avoidance patterns become entrenched.",
    faqs: [
      { q: "Is gross motor OT the same as physiotherapy?", a: "There is overlap. Pediatric OT addresses gross motor skills within the context of daily participation — play, school, and self-care." },
      { q: "How does aquatic therapy help gross motor skills?", a: "Water reduces gravity's impact, allowing children to practice balance and strength in a safe, enjoyable environment." },
      { q: "Can gross motor skills improve after age 8?", a: "Yes. Consistent, targeted intervention produces meaningful gains at any age within our 0–14 year range." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy", "brain-gym", "mnri"],
  },
];
