import { additionalConditionsContent } from "./conditions-content-additional";
import { applyParentVoiceToCondition } from "./parent-voice-conditions";

export type ConditionContent = {
  slug: string;
  title: string;
  metaDescription: string;
  keywords: string[];
  intro: string;
  symptoms: string[];
  challenges: string[];
  therapyRole: string[];
  benefits: string[];
  whenToBegin: string;
  faqs: { q: string; a: string }[];
  relatedServices: string[];
};

export const conditionsContent: ConditionContent[] = [
  {
    slug: "autism-spectrum-disorder",
    title: "Autism Spectrum Disorder (ASD)",
    metaDescription: "Pediatric OT for autism in Mumbai & Kandivali. Dr. Sharuja Sarap supports sensory regulation, daily routines & social participation for children with ASD.",
    keywords: ["autism occupational therapy Mumbai", "ASD therapy Kandivali", "sensory therapy autism Mumbai"],
    intro: "Every autistic child experiences the world in their own unique way. Some children may communicate differently, respond more strongly to sounds, lights, touch, or movement, prefer predictable routines, or find social situations difficult to understand. While every child is different, understanding their unique needs can help create opportunities for meaningful growth, learning, and participation.",
    symptoms: [
      "Prefers to play alone or interacts differently with other children (Social Communication & Social Interaction)",
      "Uses fewer words than expected, repeats phrases, or finds it difficult to express needs (Communication Difficulties)",
      "Becomes upset when routines change unexpectedly (Cognitive Flexibility & Emotional Regulation)",
      "Covers ears during everyday sounds such as mixers, hand dryers, school assemblies, or traffic (Auditory Sensory Sensitivity)",
      "Refuses certain foods because of texture, smell, colour, or appearance (Sensory Processing Differences)",
      "Avoids certain clothing, tags, socks, shoes, or haircuts (Tactile Sensory Sensitivity)",
      "Enjoys repeatedly spinning objects, lining up toys, or watching moving objects (Repetitive Behaviours & Restricted Interests)",
      "Has difficulty joining group activities, birthday parties, or playground games (Social Participation)",
      "Finds dressing, feeding, grooming, or toileting more difficult than expected for age (Activities of Daily Living Skills)",
      "Appears overwhelmed, frustrated, or has meltdowns in busy environments (Sensory Overload & Self-Regulation Challenges)",
    ],
    challenges: [
      "Family outings often feel stressful because your child becomes overwhelmed",
      "Everyday tasks such as dressing, mealtimes, grooming, or transitions frequently lead to frustration",
      "Sensory sensitivities interfere with participation at home, school, or community settings",
      "Your child avoids age-appropriate play activities or social interaction",
      "Teachers have concerns regarding learning, behaviour, attention, or classroom participation",
      "You feel your child needs additional support to manage everyday activities more comfortably",
      "Your child is not using words as expected, finds conversations difficult, or struggles to express wants and needs",
    ],
    therapyRole: [
      "Understanding and supporting sensory needs (Sensory Processing & Regulation)",
      "Improving emotional regulation and coping strategies (Self-Regulation Skills)",
      "Developing play skills and social participation (Social Engagement & Interaction)",
      "Building fine motor skills needed for writing, drawing, cutting, and classroom tasks (Fine Motor Development)",
      "Improving coordination, balance, body awareness, and movement confidence (Gross Motor Skills & Motor Planning)",
      "Supporting dressing, feeding, grooming, and toileting skills (Daily Living Skills)",
      "Enhancing attention and participation in school activities (School Readiness & Classroom Participation)",
      "Promoting independence in everyday routines (Functional Independence)",
    ],
    benefits: [
      "Reduced frequency and intensity of meltdowns",
      "Greater tolerance of everyday environments — school, shops, social gatherings",
      "Improved independence in self-care routines",
      "Stronger motor skills for play, sports, and classroom tasks",
      "Increased engagement in family activities and peer interaction",
      "Better sleep and mealtime participation",
      "Parents equipped with practical strategies for daily life",
    ],
    whenToBegin: "A diagnosis does not define a child. Every child has their own strengths, interests, personality, and way of experiencing the world. Our goal is not to change who a child is, but to better understand their needs, support their strengths, and help them participate more successfully in the activities that matter most to them and their families. Consider seeking support if: family outings often feel stressful, everyday tasks frequently lead to frustration, sensory sensitivities interfere with participation, your child avoids age-appropriate play, teachers have concerns, or your child struggles to express wants and needs.",
    faqs: [
      { q: "Does my child need an autism diagnosis before starting OT?", a: "No. Therapy can begin based on observed sensory, motor, or participation challenges while diagnostic processes continue." },
      { q: "How is OT for autism different from ABA?", a: "OT addresses sensory-motor foundations for daily participation. ABA focuses on behavior modification. Many families benefit from both approaches." },
      { q: "Will therapy try to make my child 'normal'?", a: "Never. We build sensory, motor, and daily living skills that help your child participate more fully — while respecting who they are." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "handwriting-training"],
  },
  {
    slug: "adhd",
    title: "Attention Deficit Hyperactivity Disorder (ADHD)",
    metaDescription: "ADHD occupational therapy in Mumbai. Dr. Sharuja Sarap helps children with attention, impulse control & executive function through OT and Brain Gym in Kandivali.",
    keywords: ["ADHD occupational therapy Mumbai", "attention therapy Kandivali", "Brain Gym ADHD Mumbai"],
    intro: "Children with ADHD are often bright, curious, creative, and full of energy. However, they may experience challenges with attention, impulse control, organization, emotional regulation, and managing everyday demands. ADHD is a neurodevelopmental condition that affects how the brain regulates attention, activity levels, self-control, and executive functioning skills. These challenges are not caused by laziness, poor parenting, or lack of intelligence. Many children with ADHD want to do well but may find it difficult to consistently manage tasks, emotions, and expectations.",
    symptoms: [
      "Starts a task but quickly moves on to something else before finishing (Sustained Attention Difficulties)",
      "Frequently loses water bottles, homework, books, toys, or personal belongings (Organization & Executive Functioning Challenges)",
      "Appears to be listening but misses instructions or forgets what was said (Working Memory Difficulties)",
      "Constantly fidgets, taps, squirms, or struggles to remain seated (Hyperactivity)",
      "Interrupts conversations, blurts out answers, or has difficulty waiting their turn (Impulsivity)",
      "Becomes frustrated quickly when things don't go as expected (Emotional Regulation Difficulties)",
      "Needs frequent reminders to complete simple daily tasks (Task Initiation & Task Completion Difficulties)",
      "Appears disorganized despite understanding the work (Executive Function Challenges)",
      "Finds homework and classroom tasks more difficult than expected (Academic Participation Challenges)",
      "Has difficulty transitioning between activities or routines (Self-Regulation Difficulties)",
    ],
    challenges: [
      "Your child's attention difficulties are affecting learning or daily activities",
      "Homework has become a daily struggle",
      "Emotional outbursts occur frequently",
      "Teachers consistently report concerns regarding focus, behaviour, or organization",
      "Your child becomes frustrated because they know what to do but struggle to do it consistently",
      "Daily routines require constant reminders and supervision",
    ],
    therapyRole: [
      "Improving attention and concentration during daily tasks (Attention Regulation)",
      "Developing planning, organization, and problem-solving skills (Executive Functioning Skills)",
      "Supporting emotional regulation and frustration management (Self-Regulation Skills)",
      "Building body awareness and movement control (Motor Coordination & Proprioceptive Processing)",
      "Developing strategies for classroom participation (School Participation)",
      "Improving handwriting and task endurance (Fine Motor & Visual-Motor Skills)",
      "Supporting routine management and independence (Functional Independence)",
      "Creating sensory strategies that help children stay regulated and engaged (Sensory Regulation)",
    ],
    benefits: [
      "Improved focus during seated tasks and classroom activities",
      "Better impulse control and emotional self-management",
      "Stronger organizational skills and homework completion",
      "Increased confidence and reduced frustration",
      "Practical classroom strategies teachers can implement",
      "Parents equipped with home routines that support regulation",
    ],
    whenToBegin: "Children with ADHD often bring creativity, curiosity, enthusiasm, energy, and unique ways of thinking to the world around them. By understanding their needs and supporting skill development, we can help them participate more confidently and successfully in everyday life. Consider seeking support if: attention difficulties are affecting learning or daily activities, homework has become a daily struggle, emotional outbursts occur frequently, teachers consistently report concerns, your child becomes frustrated because they know what to do but struggle to do it consistently, or daily routines require constant reminders and supervision.",
    faqs: [
      { q: "Can OT replace ADHD medication?", a: "OT and medication address different aspects of ADHD. Many families use OT alongside medical management. We do not prescribe medication but collaborate with your pediatrician." },
      { q: "How does Brain Gym help ADHD?", a: "Targeted movements activate neural pathways for focus, coordination, and learning readiness — complementing traditional OT strategies." },
      { q: "Will my hyperactive child have to sit still in sessions?", a: "No. Sessions incorporate movement and sensory input. We work with your child's energy, not against it." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "handwriting-training"],
  },
  {
    slug: "cerebral-palsy",
    title: "Cerebral Palsy (CP)",
    metaDescription: "Pediatric OT for cerebral palsy in Mumbai. Dr. Sharuja Sarap supports posture, motor planning & daily participation in Kandivali West.",
    keywords: ["cerebral palsy occupational therapy Mumbai", "CP therapy Kandivali", "pediatric OT cerebral palsy"],
    intro: "Cerebral Palsy (CP) is a neurological condition that affects movement, posture, muscle control, and coordination. Every child with cerebral palsy is unique. Some children may experience mild difficulties with movement, while others may require more support with everyday activities. Although cerebral palsy affects movement, it does not define a child's personality, abilities, interests, or potential. With appropriate support and opportunities, children can continue to learn, participate, and develop meaningful skills throughout their lives.",
    symptoms: [
      "Reaches developmental milestones later than expected (Developmental Delay)",
      "Appears stiff, tight, or has difficulty relaxing muscles (Increased Muscle Tone / Spasticity)",
      "Appears floppy or has difficulty maintaining posture (Low Muscle Tone / Hypotonia)",
      "Has difficulty sitting, standing, crawling, walking, or maintaining balance (Gross Motor Challenges)",
      "Tires easily during play or daily activities (Reduced Endurance)",
      "Has difficulty using both hands together during activities (Bilateral Coordination Difficulties)",
      "Struggles with dressing, feeding, writing, or manipulating small objects (Fine Motor Challenges)",
      "Finds playground activities more difficult than peers (Motor Coordination Difficulties)",
      "Requires assistance for age-appropriate self-care activities (Functional Independence Challenges)",
      "Shows frustration when physical limitations interfere with participation (Participation Challenges)",
    ],
    challenges: [
      "Your child has trouble participating in daily activities because of movement challenges",
      "Self-care skills such as dressing, feeding, or grooming require significant assistance",
      "Hand function affects play, school activities, or independence",
      "Balance, posture, or coordination difficulties limit participation",
      "You would like support in helping your child become more independent in everyday life",
      "You are looking for strategies that can be incorporated into home, school, or community environments",
    ],
    therapyRole: [
      "Improving hand function, grasp, and object manipulation (Fine Motor Development)",
      "Enhancing posture, balance, and body control during activities (Postural Control)",
      "Supporting dressing, feeding, grooming, and self-care skills (Activities of Daily Living)",
      "Developing play and leisure participation (Play Skills & Participation)",
      "Improving bilateral coordination and hand use (Upper Limb Function)",
      "Supporting classroom participation and handwriting when appropriate (School Participation)",
      "Recommending adaptive equipment or environmental modifications when needed (Assistive Technology & Adaptations)",
      "Working towards greater independence and participation in everyday routines (Functional Independence)",
    ],
    benefits: [
      "Improved functional independence in daily routines",
      "Better posture and reduced compensatory movement patterns",
      "Increased participation in play, school, and community activities",
      "Greater confidence and reduced frustration",
      "Parents trained in safe handling and home exercise programs",
      "Appropriate adaptive equipment recommendations",
      "Celebration of every functional gain, however small it may seem",
    ],
    whenToBegin: "For children with cerebral palsy, progress may look different for every individual. Sometimes it is learning to crawl, stand or walk, hold a spoon independently, button a shirt, participate in a classroom activity, play with friends, or accomplish a personal goal that once felt difficult. Our focus is on supporting meaningful participation, independence, and opportunities for children to engage in the activities that matter most to them and their families.",
    faqs: [
      { q: "Does Dr. Sharuja Sarap work with other therapists for CP?", a: "Yes. We collaborate with physiotherapists, speech therapists, and educators for coordinated, family-centered care." },
      { q: "Is aquatic therapy safe for children with CP?", a: "Yes, with certified supervision. Water provides a safe environment for movement practice with reduced gravity." },
      { q: "Can OT help my child use their hands better?", a: "Yes. Fine motor OT addresses grasp patterns, hand strength, and tool use for self-care and classroom tasks." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy"],
  },
  {
    slug: "developmental-delay",
    title: "Developmental Delay",
    metaDescription: "Early intervention for developmental delay in Mumbai. Dr. Sharuja Sarap provides pediatric OT in Kandivali for motor, sensory & daily living milestones.",
    keywords: ["developmental delay therapy Mumbai", "early intervention Kandivali", "pediatric OT developmental delay"],
    intro: "Children develop at their own pace, but there are certain milestones that help us understand how they are progressing. Sometimes, a child may take longer than expected to develop skills related to movement, play, communication, learning, self-care, or social interaction. A developmental delay does not tell us how far a child can go—it simply indicates that they may need additional support to develop certain skills and participate more confidently in everyday activities.",
    symptoms: [
      "Reaches milestones later than other children of a similar age (Developmental Milestone Delays)",
      "Takes longer to learn new skills such as dressing, feeding, or using utensils (Adaptive Skill Delays)",
      "Shows limited interest in age-appropriate play activities (Play Skill Delays)",
      "Has difficulty following simple instructions or routines (Cognitive & Learning Challenges)",
      "Appears less independent than peers of the same age (Functional Independence Delays)",
      "Struggles with balance, coordination, running, jumping, or climbing (Gross Motor Delays)",
      "Finds activities such as colouring, drawing, building blocks, or using scissors difficult (Fine Motor Delays)",
      "Has difficulty interacting, sharing, or participating with other children (Social Participation Challenges)",
      "Gets frustrated when tasks seem difficult or require extra effort (Reduced Confidence & Task Persistence)",
    ],
    challenges: [
      "You feel your child is consistently behind in multiple developmental areas",
      "Everyday tasks seem much harder for your child compared to peers",
      "Your child becomes frustrated when trying to learn new skills",
      "Teachers, doctors, or caregivers have raised developmental concerns",
      "You are unsure whether your child's development is progressing as expected",
    ],
    therapyRole: [
      "Building fine motor skills for play, learning, and self-care (Fine Motor Development)",
      "Improving balance, coordination, and body control (Gross Motor Development)",
      "Developing play skills and social participation (Play & Social Development)",
      "Supporting dressing, feeding, toileting, and daily routines (Activities of Daily Living)",
      "Enhancing attention, learning readiness, and task participation (School Readiness Skills)",
      "Improving confidence and independence during everyday activities (Functional Participation)",
      "Supporting sensory processing and regulation when needed (Sensory Integration Support)",
    ],
    benefits: [
      "Accelerated progress toward developmental milestones",
      "Improved confidence and willingness to try new activities",
      "Parents equipped with practical daily strategies",
      "Better school readiness when the time comes",
      "Reduced parental anxiety through clear progress tracking",
      "Child experiences therapy as play, not pressure",
      "Foundation for long-term independence and participation",
    ],
    whenToBegin: "The moment you notice your child falling behind peers in multiple areas is the right time to consult. Consider seeking support if: you feel your child is consistently behind in multiple developmental areas, everyday tasks seem much harder for your child compared to peers, your child becomes frustrated when trying to learn new skills, teachers, doctors, or caregivers have raised developmental concerns, or you are unsure whether your child's development is progressing as expected.",
    faqs: [
      { q: "Will my child catch up to peers?", a: "Many children make significant progress with early, consistent intervention. Outcomes depend on the underlying cause and intervention intensity." },
      { q: "How is developmental delay diagnosed?", a: "Pediatricians and developmental specialists use standardized assessments. OT assessment complements medical evaluation with functional skill analysis." },
      { q: "Can therapy start before a formal diagnosis?", a: "Absolutely. If you have concerns, a consultation can begin the support process immediately." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy", "brain-gym"],
  },
  {
    slug: "sensory-processing-difficulties",
    title: "Sensory Processing Difficulties",
    metaDescription: "Sensory integration therapy in Mumbai & Kandivali. Dr. Sharuja Sarap helps children regulate sensory input for calmer, more confident daily participation.",
    keywords: ["sensory integration therapy Mumbai", "sensory processing disorder Kandivali", "sensory OT Mumbai"],
    intro: "Every day, our brains receive information from our senses—what we see, hear, touch, taste, smell, and how our bodies move. Most of us automatically process this information without thinking about it. Some children, however, experience sensory information differently. They may be extremely sensitive to certain sensations, actively seek sensory experiences, or find it difficult to interpret sensory information accurately. Sensory processing difficulties can affect attention, behaviour, emotions, learning, movement, sleep, feeding, and participation in everyday activities.",
    symptoms: [
      "Covers ears during vacuum cleaners, mixers, school bells, or crowded places (Auditory Sensitivity)",
      "Refuses certain clothes because of tags, seams, socks, or fabric textures (Tactile Sensitivity)",
      "Avoids haircuts, nail trimming, tooth brushing, or face washing (Touch Sensitivity)",
      "Is bothered by bright lights, strong smells, or busy environments (Visual & Olfactory Sensitivity)",
      "Becomes overwhelmed in shopping malls, birthday parties, classrooms, or family gatherings (Sensory Over-Responsivity)",
      "Loves spinning, swinging, jumping, climbing, or crashing into furniture (Vestibular & Proprioceptive Seeking)",
      "Constantly touches people, objects, or surfaces (Sensory Seeking Behaviour)",
      "Chews on clothing, pencils, toys, or other non-food items (Oral Sensory Seeking)",
      "Appears constantly 'on the go' and has difficulty sitting still (Movement Seeking)",
      "Uses excessive force during play, writing, or everyday tasks (Body Awareness Difficulties)",
      "Appears clumsy or frequently bumps into objects (Proprioceptive Processing Difficulties)",
      "Has trouble judging personal space (Body Awareness Challenges)",
      "Finds balance activities difficult (Vestibular Processing Difficulties)",
      "Struggles to coordinate movements during play and sports (Motor Planning Difficulties / Praxis Challenges)",
    ],
    challenges: [
      "Sensory challenges are affecting family routines, mealtimes, school participation, or sleep",
      "Your child frequently avoids or seeks sensory experiences in ways that interfere with daily life",
      "Everyday environments often lead to overwhelm, distress, or meltdowns",
      "Movement, balance, coordination, or body awareness difficulties affect participation",
      "You feel sensory challenges may be contributing to behavioural or emotional difficulties",
    ],
    therapyRole: [
      "Identifying individual sensory preferences and challenges (Sensory Profile Assessment)",
      "Developing sensory regulation strategies (Self-Regulation Skills)",
      "Supporting attention, participation, and learning (Sensory-Based Intervention)",
      "Improving body awareness, coordination, and motor planning (Praxis Development)",
      "Helping children participate more comfortably in school, social, and community environments (Functional Participation)",
      "Providing practical strategies for home, school, and daily routines (Family & Environmental Support)",
      "Supporting emotional regulation and coping skills (Co-Regulation & Self-Regulation)",
    ],
    benefits: [
      "Reduced meltdown frequency and faster recovery",
      "Greater tolerance of everyday sensory experiences",
      "Improved attention and engagement after regulation",
      "Expanded food acceptance and mealtime calm",
      "Better sleep and overall mood regulation",
      "Parents understand the 'why' behind behaviors",
      "Child develops self-advocacy for sensory needs",
    ],
    whenToBegin: "Not sure if it's sensory? If your child often says, 'it's too loud', 'it hurts', 'I don't like that', constantly seeks movement, or struggles in busy environments, sensory processing may be worth exploring. Consider seeking support if: sensory challenges are affecting family routines, mealtimes, school participation, or sleep; your child frequently avoids or seeks sensory experiences in ways that interfere with daily life; everyday environments often lead to overwhelm, distress, or meltdowns; movement, balance, coordination, or body awareness difficulties affect participation; or you feel sensory challenges may be contributing to behavioural or emotional difficulties.",
    faqs: [
      { q: "Is sensory processing disorder a real diagnosis?", a: "Sensory processing difficulties are well-documented in occupational therapy literature. While not always a standalone medical diagnosis, the functional impact is real and treatable." },
      { q: "Will my child outgrow sensory issues?", a: "Some children adapt naturally; many benefit from targeted therapy to build regulation skills that last into adulthood." },
      { q: "What is a sensory gym?", a: "A therapy space equipped with swings, climbing structures, textures, and movement tools designed for sensory integration activities." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy"],
  },
  {
    slug: "learning-difficulties",
    title: "Learning Disabilities",
    metaDescription: "OT for learning difficulties in Mumbai. Dr. Sharuja Sarap uses movement-based approaches & Brain Gym in Kandivali to support reading, writing & classroom success.",
    keywords: ["learning difficulties occupational therapy Mumbai", "learning support Kandivali", "Brain Gym learning Mumbai"],
    intro: "Every child learns differently. Some children may work harder than their peers to develop skills related to reading, writing, spelling, mathematics, attention, memory, or organization. Despite having average or above-average intelligence, they may continue to struggle with specific academic tasks. Learning disabilities are not a reflection of laziness, lack of effort, or poor parenting. Often, children know the answer but find it difficult to process, organize, remember, or express information in the expected way.",
    symptoms: [
      "Takes much longer than expected to complete homework (Learning & Processing Difficulties)",
      "Struggles to remember letters, numbers, spellings, or mathematical concepts (Memory & Academic Skill Challenges)",
      "Reads slowly, skips words, or avoids reading activities (Reading Difficulties / Dyslexia-Related Features)",
      "Finds writing assignments frustrating and difficult to organize (Written Expression Difficulties)",
      "Frequently forgets instructions, even after hearing them several times (Working Memory Difficulties)",
      "Knows answers verbally but struggles to write them on paper (Processing & Expression Challenges)",
      "Appears intelligent and capable but underperforms academically (Learning Differences)",
      "Avoids homework, reading, or school-related activities (Academic Avoidance)",
      "Experiences frustration, low confidence, or anxiety related to schoolwork (Self-Esteem & Academic Confidence Concerns)",
      "Frequently says, \"I'm not good at school\" or \"I can't do it\" (Reduced Academic Self-Confidence)",
    ],
    challenges: [
      "Homework regularly leads to frustration, tears, or conflict",
      "Your child works hard but continues to struggle academically",
      "Teachers have raised concerns about learning, writing, attention, or classroom participation",
      "Academic challenges are affecting confidence and motivation",
      "You feel your child is capable of more but is finding it difficult to demonstrate their abilities",
    ],
    therapyRole: [
      "Improving attention, concentration, and task persistence (Attention & Executive Functioning)",
      "Developing visual perception and visual-motor integration skills (Visual Processing Skills)",
      "Supporting handwriting, written expression, and classroom participation (Academic Participation Skills)",
      "Building organization, planning, and study skills (Executive Functioning Development)",
      "Strengthening memory and task management strategies (Learning Readiness Skills)",
      "Improving confidence and independence during academic tasks (Functional School Participation)",
      "Collaborating with families and schools to support learning success (Environmental & Educational Support)",
    ],
    benefits: [
      "Improved reading readiness and visual tracking",
      "Clearer, faster handwriting and written expression",
      "Better attention during learning tasks",
      "Increased homework completion and reduced battles",
      "Classroom accommodations that level the playing field",
      "Child understands their learning profile and strengths",
      "Parents equipped to advocate effectively at school",
    ],
    whenToBegin: "Consider seeking support if: homework regularly leads to frustration, tears, or conflict; your child works hard but continues to struggle academically; teachers have raised concerns about learning, writing, attention, or classroom participation; academic challenges are affecting confidence and motivation; or you feel your child is capable of more but is finding it difficult to demonstrate their abilities.",
    faqs: [
      { q: "Is OT the same as tutoring?", a: "No. Tutoring teaches content. OT addresses the sensory-motor and processing foundations that make learning possible." },
      { q: "Can OT help with dyslexia?", a: "OT addresses visual-motor, attention, and processing components that often co-occur with dyslexia, complementing specialized reading programs." },
      { q: "Does Dr. Sharuja Sarap diagnose learning disabilities?", a: "OT assessment identifies functional skill gaps. Formal learning disability diagnosis is made by educational psychologists or developmental pediatricians." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "handwriting-training"],
  },
  {
    slug: "motor-coordination-challenges",
    title: "Motor Coordination Challenges",
    metaDescription: "Motor coordination therapy for children in Mumbai. Dr. Sharuja Sarap improves balance, motor planning & physical confidence in Kandivali West.",
    keywords: ["motor coordination therapy Mumbai", "dyspraxia OT Kandivali", "coordination therapy children Mumbai"],
    intro: "Some children find it difficult to plan, coordinate, and execute movements efficiently. Tasks that seem simple for other children—such as catching a ball, riding a bicycle, using scissors, climbing playground equipment, or participating in sports—may require significantly more effort. Motor coordination difficulties can affect both large body movements (Gross Motor Skills) and hand skills (Fine Motor Skills), impacting participation at home, school, and during play.",
    symptoms: [
      "Frequently trips, bumps into objects, or appears clumsy (Motor Coordination Difficulties)",
      "Avoids sports, playground activities, or physical games (Gross Motor Challenges)",
      "Has difficulty learning new movement-based skills such as cycling, skipping, swimming, or ball games (Motor Planning Difficulties / Dyspraxia Features)",
      "Struggles to catch, throw, kick, or coordinate movements during play (Bilateral Coordination Challenges)",
      "Appears awkward when running, jumping, climbing, or balancing (Balance & Coordination Difficulties)",
      "Has difficulty using scissors, colouring, drawing, or manipulating small objects (Fine Motor Challenges)",
      "Becomes tired more quickly than peers during physical activities (Reduced Motor Endurance)",
      "Avoids activities that require coordination because they feel difficult or embarrassing (Reduced Movement Confidence)",
      "Takes longer than expected to learn everyday motor skills (Motor Learning Difficulties)",
      "Becomes frustrated when physical tasks seem harder than they should (Participation Challenges)",
    ],
    challenges: [
      "Your child avoids physical activities because they find them difficult",
      "Coordination challenges are affecting participation in school, sports, or play",
      "Hand skills are making writing, dressing, or self-care tasks difficult",
      "Your child appears significantly less confident in movement-based activities compared to peers",
      "Everyday motor tasks require more effort than expected for their age",
    ],
    therapyRole: [
      "Improving balance, coordination, and body awareness (Gross Motor Development)",
      "Strengthening motor planning and movement sequencing skills (Praxis & Motor Planning)",
      "Developing hand skills for writing, dressing, feeding, and classroom activities (Fine Motor Development)",
      "Improving bilateral coordination and postural stability (Postural Control & Coordination)",
      "Building confidence during sports, play, and recreational activities (Participation & Confidence Building)",
      "Supporting school-related motor tasks such as handwriting and classroom participation (Functional Academic Skills)",
      "Encouraging greater independence in everyday activities (Functional Independence)",
    ],
    benefits: [
      "Improved balance, coordination, and motor planning",
      "Greater willingness to attempt new physical activities",
      "Better playground and sports participation",
      "Improved handwriting and tool use",
      "Increased physical confidence and self-esteem",
      "Reduced clumsiness-related injuries and frustration",
    ],
    whenToBegin: "Consider seeking support if: your child avoids physical activities because they find them difficult; coordination challenges are affecting participation in school, sports, or play; hand skills are making writing, dressing, or self-care tasks difficult; your child appears significantly less confident in movement-based activities compared to peers; or everyday motor tasks require more effort than expected for their age.",
    faqs: [
      { q: "Is clumsiness always dyspraxia?", a: "Not always, but persistent coordination difficulties across multiple activities warrant professional assessment." },
      { q: "Can coordination improve with age?", a: "Some children improve naturally; many benefit significantly from targeted OT and aquatic therapy." },
      { q: "Does aquatic therapy help coordination?", a: "Yes. Water provides a safe, supportive environment for practicing balance and movement patterns." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy", "brain-gym"],
  },
  {
    slug: "handwriting-difficulties",
    title: "Handwriting Difficulties",
    metaDescription: "Handwriting therapy for children in Mumbai. Dr. Sharuja Sarap is HWT-certified, helping kids build legible writing & classroom confidence in Kandivali.",
    keywords: ["handwriting therapy Mumbai", "Handwriting Without Tears Kandivali", "handwriting OT Mumbai"],
    intro: "Handwriting is much more than putting letters on paper. It requires the successful coordination of visual, motor, sensory, cognitive, and postural skills working together at the same time. When handwriting becomes difficult, children often spend so much energy trying to form letters that they struggle to keep up with classroom demands, express their ideas, or complete written work confidently.",
    symptoms: [
      "Uses an awkward or inefficient pencil grasp (Pencil Grip Difficulties)",
      "Writes slowly compared to classmates (Writing Speed Difficulties)",
      "Complains of hand pain or fatigue during writing tasks (Reduced Hand Strength & Endurance)",
      "Forms letters inconsistently or reverses letters and numbers (Letter Formation Difficulties)",
      "Has messy handwriting that is difficult to read (Handwriting Legibility Challenges)",
      "Struggles to stay within lines or maintain spacing between words (Visual-Motor Integration Difficulties)",
      "Avoids writing activities, homework, or written assignments (Reduced Writing Confidence)",
      "Knows the answer but finds it difficult to get thoughts onto paper (Written Expression Challenges)",
      "Takes significantly longer to complete schoolwork involving writing (Classroom Participation Difficulties)",
      "Becomes frustrated, anxious, or upset when asked to write (Academic Confidence Concerns)",
    ],
    challenges: [
      "Handwriting is affecting your child's academic performance",
      "Writing tasks consistently cause frustration or avoidance",
      "Your child struggles to complete written work within expected timeframes",
      "Teachers have raised concerns regarding handwriting quality or speed",
      "Your child appears capable of answering verbally but struggles when writing",
      "Handwriting difficulties are affecting confidence and classroom participation",
    ],
    therapyRole: [
      "Developing efficient pencil grasp and control (Pencil Skills)",
      "Improving hand strength, dexterity, and endurance (Fine Motor Development)",
      "Enhancing visual-motor integration and eye-hand coordination (Visual-Motor Skills)",
      "Improving letter formation, spacing, alignment, and writing organization (Handwriting Skills)",
      "Supporting posture and body stability during seated work (Postural Control)",
      "Building confidence and participation in classroom writing activities (Academic Participation)",
      "Identifying underlying factors contributing to handwriting difficulties (Functional Assessment)",
    ],
    benefits: [
      "Legible, consistent handwriting for classroom and exams",
      "Improved writing speed and reduced hand fatigue",
      "Functional pencil grip that supports long-term writing",
      "Increased confidence in written work",
      "Classroom accommodations when needed",
      "Child re-engages with writing tasks willingly",
    ],
    whenToBegin: "Consider seeking support if: handwriting is affecting your child's academic performance; writing tasks consistently cause frustration or avoidance; your child struggles to complete written work within expected timeframes; teachers have raised concerns regarding handwriting quality or speed; your child appears capable of answering verbally but struggles when writing; or handwriting difficulties are affecting confidence and classroom participation.",
    faqs: [
      { q: "Will more writing practice at home fix the problem?", a: "Practice without addressing underlying grip, strength, and visual-motor issues often increases frustration. Targeted OT identifies and treats root causes." },
      { q: "Is HWT suitable for older children?", a: "Yes. HWT programs adapt to different age groups, including remediation for older students with persistent difficulties." },
      { q: "Can my child use a laptop instead?", a: "Typing is a valid accommodation, but OT addresses foundational skills that support both handwriting and keyboard use." },
    ],
    relatedServices: ["handwriting-training", "occupational-therapy", "brain-gym"],
  },
  {
    slug: "attention-difficulties",
    title: "Attention, Focus & Concentration Challenges",
    metaDescription: "Attention & focus therapy for children in Mumbai. Dr. Sharuja Sarap uses OT & Brain Gym in Kandivali to build learning readiness & sustained focus.",
    keywords: ["attention therapy children Mumbai", "focus therapy Kandivali", "learning readiness OT Mumbai"],
    intro: "Many children find it difficult to stay focused, follow instructions, complete tasks, or remain engaged in activities for extended periods of time. While attention challenges are sometimes associated with ADHD, they can also occur due to sensory processing differences, learning difficulties, emotional factors, executive functioning challenges, developmental delays, or simply because the demands being placed on the child exceed their current skills. Attention is not just about \"sitting still.\" It involves listening, processing information, staying organized, filtering distractions, remembering instructions, and completing tasks successfully.",
    symptoms: [
      "Frequently starts activities but leaves them unfinished (Sustained Attention Difficulties)",
      "Needs repeated reminders to complete simple daily tasks (Attention & Task Completion Challenges)",
      "Appears distracted by sounds, people, or activities happening around them (Difficulty Filtering Distractions)",
      "Forgets instructions shortly after hearing them (Working Memory Difficulties)",
      "Takes much longer than expected to complete homework or routine activities (Task Persistence Difficulties)",
      "Loses track of belongings such as water bottles, books, homework, or school materials (Organization Challenges)",
      "Appears to daydream or \"switch off\" during conversations or classroom activities (Attention Regulation Difficulties)",
      "Has difficulty following multi-step instructions (Processing & Working Memory Challenges)",
      "Struggles to stay focused during table-top activities, homework, reading, or writing tasks (Sustained Concentration Difficulties)",
      "Becomes frustrated when tasks require prolonged effort or concentration (Mental Endurance Challenges)",
    ],
    challenges: [
      "Your child frequently struggles to complete age-appropriate tasks",
      "Homework, reading, or writing activities consistently take much longer than expected",
      "Teachers regularly report concerns regarding attention, participation, or task completion",
      "Daily routines require constant reminders and supervision",
      "Attention difficulties are affecting learning, confidence, independence, or participation in everyday activities",
      "You feel your child understands what to do but finds it difficult to stay engaged long enough to complete it",
    ],
    therapyRole: [
      "Improving attention, concentration, and task engagement (Attention Regulation Skills)",
      "Developing planning, organization, and time-management abilities (Executive Functioning Skills)",
      "Addressing sensory factors that may affect focus and participation (Sensory Processing Support)",
      "Building routines and strategies for completing daily tasks successfully (Functional Organization Skills)",
      "Supporting learning readiness and classroom participation (School Participation Skills)",
      "Developing self-monitoring and self-regulation strategies (Self-Regulation Skills)",
      "Collaborating with families and educators to create supportive environments (Environmental Modifications & Support)",
    ],
    benefits: [
      "Improved sustained attention during tasks",
      "Better task completion at home and school",
      "Practical strategies for managing distractions",
      "Increased learning readiness and academic engagement",
      "Child learns to recognize and manage their attention patterns",
      "Reduced parent redirection and homework battles",
    ],
    whenToBegin: "Consider seeking support if: your child frequently struggles to complete age-appropriate tasks; homework, reading, or writing activities consistently take much longer than expected; teachers regularly report concerns regarding attention, participation, or task completion; daily routines require constant reminders and supervision; attention difficulties are affecting learning, confidence, independence, or participation in everyday activities; or you feel your child understands what to do but finds it difficult to stay engaged long enough to complete it.",
    faqs: [
      { q: "Is this the same as ADHD therapy?", a: "Attention difficulties overlap significantly with ADHD, but OT also supports children with focus challenges who do not meet full ADHD criteria." },
      { q: "How quickly can attention improve?", a: "Many families notice changes within 4–8 weeks of consistent sessions and home practice." },
      { q: "Do you recommend reduced screen time?", a: "We guide families on balanced routines. Excessive unstructured screen time can impact attention and sleep, affecting therapy progress." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "handwriting-training"],
  },
];

export const allConditionsContent = [...conditionsContent, ...additionalConditionsContent];

export function getConditionContent(slug: string) {
  const condition = allConditionsContent.find((c) => c.slug === slug);
  if (!condition) return undefined;
  return applyParentVoiceToCondition(condition);
}
