import { additionalConditionsContent } from "./conditions-content-additional";

export type ConditionContent = {
  slug: string;
  title: string;
  metaDescription: string;
  keywords: string[];
  intro: string;
  symptoms: string[];
  challenges: string[];
  therapyRole: string[];
  benefits: string[];
  whenToBegin: string;
  faqs: { q: string; a: string }[];
  relatedServices: string[];
};

export const conditionsContent: ConditionContent[] = [
  {
    slug: "autism-spectrum-disorder",
    title: "Autism Spectrum Disorder",
    metaDescription: "Pediatric OT for autism in Mumbai & Kandivali. Dr. Sharuja Sarap supports sensory regulation, daily routines & social participation for children with ASD.",
    keywords: ["autism occupational therapy Mumbai", "ASD therapy Kandivali", "sensory therapy autism Mumbai"],
    intro: "Autism Spectrum Disorder (ASD) affects how children perceive, process, and respond to the world around them. At Thrive with sharuja in Kandivali West, Mumbai, Dr. Sharuja Sarap provides compassionate, evidence-informed occupational therapy that honors each child's unique way of learning, communicating, and connecting. Rather than trying to change who your child is, our approach builds the sensory, motor, and daily living foundations that help children with ASD participate more fully in family life, school, and community.",
    symptoms: [
      "Difficulty with sensory processing — over- or under-reacting to sounds, textures, lights, or movement",
      "Challenges with transitions and changes in routine",
      "Delayed or atypical motor skills — clumsiness, poor coordination, or difficulty with new physical tasks",
      "Limited engagement in pretend play or social interaction",
      "Repetitive behaviors or intense focus on specific interests",
      "Difficulty with self-care tasks — dressing, feeding, toileting",
      "Avoidance of certain foods, textures, or environments",
      "Difficulty understanding personal space and social cues",
    ],
    challenges: [
      "Sensory overload in busy environments like malls, classrooms, or birthday parties",
      "Meltdowns triggered by unexpected changes or overwhelming input",
      "Difficulty participating in group activities and peer play",
      "Frustration with fine motor tasks like writing, cutting, or buttoning",
      "Sleep disruption linked to sensory dysregulation",
      "Parent stress navigating daily routines and public outings",
      "School challenges with attention, handwriting, and classroom tolerance",
    ],
    therapyRole: [
      "Comprehensive sensory profile assessment to understand your child's unique sensory needs",
      "Sensory integration therapy to improve regulation and reduce overwhelm",
      "Development of personalized sensory diets and calming strategies for home and school",
      "Fine and gross motor skill building through structured, play-based activities",
      "Daily living skills training — dressing, feeding, grooming, and toileting routines",
      "Social participation support through guided play and turn-taking activities",
      "Collaboration with parents and schools for consistent environmental modifications",
      "Emotional regulation strategies using movement, deep pressure, and visual supports",
    ],
    benefits: [
      "Reduced frequency and intensity of meltdowns",
      "Greater tolerance of everyday environments — school, shops, social gatherings",
      "Improved independence in self-care routines",
      "Stronger motor skills for play, sports, and classroom tasks",
      "Increased engagement in family activities and peer interaction",
      "Better sleep and mealtime participation",
      "Parents equipped with practical strategies for daily life",
      "Child builds confidence in their own abilities and preferences",
    ],
    whenToBegin: "Early intervention makes a significant difference for children with ASD. If you notice sensory sensitivities, motor delays, or participation challenges — even before a formal diagnosis — a consultation with Dr. Sharuja Sarap can clarify whether OT is appropriate and what outcomes to expect.",
    faqs: [
      { q: "Does my child need an autism diagnosis before starting OT?", a: "No. Therapy can begin based on observed sensory, motor, or participation challenges while diagnostic processes continue." },
      { q: "How is OT for autism different from ABA?", a: "OT addresses sensory-motor foundations for daily participation. ABA focuses on behavior modification. Many families benefit from both approaches." },
      { q: "Will therapy try to make my child 'normal'?", a: "Never. Our philosophy — Belonging Without Boundaries — celebrates each child's strengths while building skills for meaningful participation." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "handwriting-training"],
  },
  {
    slug: "adhd",
    title: "ADHD",
    metaDescription: "ADHD occupational therapy in Mumbai. Dr. Sharuja Sarap helps children with attention, impulse control & executive function through OT and Brain Gym in Kandivali.",
    keywords: ["ADHD occupational therapy Mumbai", "attention therapy Kandivali", "Brain Gym ADHD Mumbai"],
    intro: "Attention Deficit Hyperactivity Disorder (ADHD) affects a child's ability to sustain focus, regulate impulses, and manage the executive functions needed for school, home, and social life. At Thrive with sharuja, Dr. Sharuja Sarap combines pediatric occupational therapy with Brain Gym® movement strategies to help children with ADHD channel their energy productively, build attention stamina, and develop the self-management skills that lead to lasting confidence.",
    symptoms: [
      "Difficulty sustaining attention during tasks or conversations",
      "Easily distracted by external stimuli or internal thoughts",
      "Impulsive actions — interrupting, grabbing, difficulty waiting turns",
      "Hyperactivity — constant movement, fidgeting, difficulty sitting still",
      "Poor organization and time management",
      "Difficulty following multi-step instructions",
      "Emotional dysregulation — quick frustration, mood swings",
      "Motor restlessness and difficulty with fine motor precision",
    ],
    challenges: [
      "Incomplete homework and classroom assignments",
      "Difficulty following classroom rules and routines",
      "Social friction from impulsive behavior or missed social cues",
      "Low self-esteem from repeated academic and behavioral feedback",
      "Parent exhaustion managing daily routines and homework battles",
      "Risk of academic underachievement despite intellectual ability",
      "Sleep difficulties affecting next-day focus and mood",
    ],
    therapyRole: [
      "Assessment of attention, executive function, and sensory-motor profile",
      "Brain Gym® activities to activate focus and learning readiness pathways",
      "Sensory strategies — movement breaks, fidget tools, weighted items — for regulation",
      "Executive function training — planning, organization, task initiation, time awareness",
      "Fine motor and handwriting support for classroom participation",
      "Environmental modification recommendations for home and school",
      "Parent coaching on consistent routines and positive behavior support",
      "Gradual building of attention stamina through structured, engaging activities",
    ],
    benefits: [
      "Improved focus during seated tasks and classroom activities",
      "Better impulse control and emotional self-management",
      "Stronger organizational skills and homework completion",
      "Increased confidence and reduced frustration",
      "Practical classroom strategies teachers can implement",
      "Parents equipped with home routines that support regulation",
      "Child learns to advocate for their own sensory and movement needs",
    ],
    whenToBegin: "If attention difficulties are affecting school performance, friendships, or family harmony — even before a formal ADHD diagnosis — early OT intervention can prevent secondary issues like low self-esteem and academic disengagement.",
    faqs: [
      { q: "Can OT replace ADHD medication?", a: "OT and medication address different aspects of ADHD. Many families use OT alongside medical management. We do not prescribe medication but collaborate with your pediatrician." },
      { q: "How does Brain Gym help ADHD?", a: "Targeted movements activate neural pathways for focus, coordination, and learning readiness — complementing traditional OT strategies." },
      { q: "Will my hyperactive child have to sit still in sessions?", a: "No. Sessions incorporate movement and sensory input. We work with your child's energy, not against it." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "handwriting-training"],
  },
  {
    slug: "cerebral-palsy",
    title: "Cerebral Palsy",
    metaDescription: "Pediatric OT for cerebral palsy in Mumbai. Dr. Sharuja Sarap supports posture, motor planning & daily participation in Kandivali West.",
    keywords: ["cerebral palsy occupational therapy Mumbai", "CP therapy Kandivali", "pediatric OT cerebral palsy"],
    intro: "Cerebral palsy affects movement, posture, and motor coordination due to early brain injury or development differences. At Thrive with sharuja in Kandivali West, Dr. Sharuja Sarap provides family-centered occupational therapy that focuses on what matters most — your child's ability to participate in daily life, play, and learning with greater independence and confidence.",
    symptoms: [
      "Muscle stiffness (spasticity) or floppiness (hypotonia)",
      "Asymmetric posture or favoring one side of the body",
      "Delayed motor milestones — sitting, crawling, walking",
      "Difficulty with fine motor tasks — grasping, writing, self-feeding",
      "Involuntary movements or tremors",
      "Balance and coordination challenges",
      "Difficulty with oral motor skills and feeding",
      "Adaptive equipment needs for daily activities",
    ],
    challenges: [
      "Limited independence in self-care — dressing, bathing, feeding",
      "Difficulty accessing school environments and participating in PE",
      "Fatigue from the extra effort required for everyday movement",
      "Social exclusion from physical play and sports",
      "Parent caregiver burden and emotional stress",
      "Need for ongoing equipment assessment and modification",
      "Transition planning for adolescence and increased independence demands",
    ],
    therapyRole: [
      "Comprehensive motor and functional assessment",
      "Postural stability and alignment training",
      "Fine and gross motor skill development through adaptive activities",
      "Self-care skills training with appropriate equipment and techniques",
      "Aquatic therapy for strength, range of motion, and confidence in movement",
      "Sensory integration to support body awareness and motor planning",
      "Home and school environmental modifications",
      "Collaboration with physiotherapists, speech therapists, and educators",
    ],
    benefits: [
      "Improved functional independence in daily routines",
      "Better posture and reduced compensatory movement patterns",
      "Increased participation in play, school, and community activities",
      "Greater confidence and reduced frustration",
      "Parents trained in safe handling and home exercise programs",
      "Appropriate adaptive equipment recommendations",
      "Celebration of every functional gain, however small it may seem",
    ],
    whenToBegin: "Early intervention is critical for cerebral palsy. The earlier therapy begins, the greater the potential for building neural connections and functional skills. It is never too late to begin — progress is possible at every age.",
    faqs: [
      { q: "Does Dr. Sharuja Sarap work with other therapists for CP?", a: "Yes. We collaborate with physiotherapists, speech therapists, and educators for coordinated, family-centered care." },
      { q: "Is aquatic therapy safe for children with CP?", a: "Yes, with certified supervision. Water provides a safe environment for movement practice with reduced gravity." },
      { q: "Can OT help my child use their hands better?", a: "Yes. Fine motor OT addresses grasp patterns, hand strength, and tool use for self-care and classroom tasks." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy"],
  },
  {
    slug: "developmental-delay",
    title: "Developmental Delay",
    metaDescription: "Early intervention for developmental delay in Mumbai. Dr. Sharuja Sarap provides pediatric OT in Kandivali for motor, sensory & daily living milestones.",
    keywords: ["developmental delay therapy Mumbai", "early intervention Kandivali", "pediatric OT developmental delay"],
    intro: "Developmental delay occurs when a child takes longer than expected to reach milestones in movement, communication, play, or self-care. Early, targeted intervention at Thrive with sharuja can significantly improve a child's trajectory. Dr. Sharuja Sarap provides warm, play-based occupational therapy in Kandivali West that meets each child where they are and builds the foundational skills for independence and joyful participation.",
    symptoms: [
      "Late achievement of motor milestones — rolling, sitting, crawling, walking",
      "Delayed fine motor skills — grasping, pointing, using utensils",
      "Limited play skills for age — not engaging in pretend or constructive play",
      "Difficulty with self-care compared to peers — feeding, dressing",
      "Reduced attention and engagement in age-appropriate activities",
      "Sensory seeking or avoiding behaviors beyond typical range",
      "Difficulty with new motor tasks or learning through imitation",
      "Global delay across multiple developmental domains",
    ],
    challenges: [
      "Parent anxiety comparing child to peers or siblings",
      "Difficulty accessing age-appropriate playgroups and activities",
      "School readiness concerns as entry age approaches",
      "Need for coordinated multi-disciplinary assessment",
      "Uncertainty about prognosis and appropriate intervention intensity",
      "Navigating diagnostic processes while seeking immediate support",
      "Balancing therapy commitments with family life",
    ],
    therapyRole: [
      "Comprehensive developmental assessment across motor, sensory, and daily living domains",
      "Play-based intervention targeting specific delayed skill areas",
      "Parent coaching on home activities that reinforce clinic progress",
      "Sensory integration activities to support nervous system development",
      "Fine and gross motor skill building through purposeful play",
      "Self-care routine establishment with step-by-step scaffolding",
      "Coordination with pediatricians and other specialists",
      "Regular progress monitoring with adjusted goals as child grows",
    ],
    benefits: [
      "Accelerated progress toward developmental milestones",
      "Improved confidence and willingness to try new activities",
      "Parents equipped with practical daily strategies",
      "Better school readiness when the time comes",
      "Reduced parental anxiety through clear progress tracking",
      "Child experiences therapy as play, not pressure",
      "Foundation for long-term independence and participation",
    ],
    whenToBegin: "The moment you notice your child falling behind peers in multiple areas is the right time to consult. Early brain plasticity means early intervention has the greatest impact. Dr. Sharuja Sarap supports children from birth through 14 years.",
    faqs: [
      { q: "Will my child catch up to peers?", a: "Many children make significant progress with early, consistent intervention. Outcomes depend on the underlying cause and intervention intensity." },
      { q: "How is developmental delay diagnosed?", a: "Pediatricians and developmental specialists use standardized assessments. OT assessment complements medical evaluation with functional skill analysis." },
      { q: "Can therapy start before a formal diagnosis?", a: "Absolutely. If you have concerns, a consultation can begin the support process immediately." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy", "brain-gym"],
  },
  {
    slug: "sensory-processing-difficulties",
    title: "Sensory Processing Difficulties",
    metaDescription: "Sensory integration therapy in Mumbai & Kandivali. Dr. Sharuja Sarap helps children regulate sensory input for calmer, more confident daily participation.",
    keywords: ["sensory integration therapy Mumbai", "sensory processing disorder Kandivali", "sensory OT Mumbai"],
    intro: "Sensory processing difficulties occur when the brain struggles to organize and respond appropriately to everyday sensory input — touch, sound, movement, taste, and visual information. For many children, this leads to meltdowns, avoidance behaviors, or constant sensory seeking that disrupts family life and learning. At Thrive with sharuja, Dr. Sharuja Sarap specializes in sensory integration therapy that helps children in Kandivali and across Mumbai build a calmer, more regulated nervous system.",
    symptoms: [
      "Extreme reactions to clothing tags, socks, or certain textures",
      "Covering ears or distress in noisy environments",
      "Avoidance of messy play, sand, or certain foods",
      "Constant movement seeking — spinning, crashing, climbing",
      "Difficulty with transitions and changes in routine",
      "Poor body awareness — bumping into things, personal space issues",
      "Overwhelmed in busy environments — malls, classrooms, parties",
      "Difficulty calming down after excitement or upset",
    ],
    challenges: [
      "Frequent meltdowns that seem unpredictable to parents",
      "Limited food variety and mealtime battles",
      "Difficulty with grooming — hair washing, nail cutting, tooth brushing",
      "School avoidance or classroom intolerance",
      "Social isolation due to sensory-triggered behaviors",
      "Parent exhaustion from constant environmental management",
      "Misunderstanding from others who see behavior as defiance",
    ],
    therapyRole: [
      "Detailed sensory profile assessment using standardized tools",
      "Ayres Sensory Integration®-informed intervention in a sensory-rich gym",
      "Development of personalized sensory diets for home and school",
      "Graded exposure to challenging sensory experiences in safe context",
      "Proprioceptive and vestibular activities for nervous system regulation",
      "Parent education on understanding and responding to sensory behaviors",
      "Environmental modification recommendations",
      "Collaboration with schools for sensory-friendly classroom setups",
    ],
    benefits: [
      "Reduced meltdown frequency and faster recovery",
      "Greater tolerance of everyday sensory experiences",
      "Improved attention and engagement after regulation",
      "Expanded food acceptance and mealtime calm",
      "Better sleep and overall mood regulation",
      "Parents understand the 'why' behind behaviors",
      "Child develops self-advocacy for sensory needs",
      "Increased participation in family outings and social activities",
    ],
    whenToBegin: "If sensory behaviors are limiting your child's participation in daily life — eating, dressing, playing, learning — sensory integration therapy can help. Early support prevents secondary issues like anxiety and social withdrawal.",
    faqs: [
      { q: "Is sensory processing disorder a real diagnosis?", a: "Sensory processing difficulties are well-documented in occupational therapy literature. While not always a standalone medical diagnosis, the functional impact is real and treatable." },
      { q: "Will my child outgrow sensory issues?", a: "Some children adapt naturally; many benefit from targeted therapy to build regulation skills that last into adulthood." },
      { q: "What is a sensory gym?", a: "A therapy space equipped with swings, climbing structures, textures, and movement tools designed for sensory integration activities." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy"],
  },
  {
    slug: "learning-difficulties",
    title: "Learning Difficulties",
    metaDescription: "OT for learning difficulties in Mumbai. Dr. Sharuja Sarap uses movement-based approaches & Brain Gym in Kandivali to support reading, writing & classroom success.",
    keywords: ["learning difficulties occupational therapy Mumbai", "learning support Kandivali", "Brain Gym learning Mumbai"],
    intro: "Learning difficulties affect a child's ability to acquire, process, and demonstrate academic skills despite adequate intelligence and instruction. Often, underlying sensory-motor and processing challenges contribute to struggles with reading, writing, math, and classroom participation. Dr. Sharuja Sarap at Thrive with sharuja addresses these foundational gaps through occupational therapy and Brain Gym® in Kandivali West, helping children access their full learning potential.",
    symptoms: [
      "Difficulty with reading fluency, comprehension, or decoding",
      "Persistent spelling and writing errors despite practice",
      "Slow processing speed — needing extra time for tasks",
      "Difficulty copying from board or organizing written work",
      "Poor visual-motor integration — puzzles, drawing, geometry",
      "Difficulty retaining and recalling learned information",
      "Avoidance of academic tasks and homework battles",
      "Discrepancy between verbal ability and written output",
    ],
    challenges: [
      "Falling behind classmates despite effort and tutoring",
      "Low self-esteem and school anxiety",
      "Behavioral issues stemming from academic frustration",
      "Parent stress navigating school meetings and assessments",
      "Risk of mislabeling as lazy or unmotivated",
      "Need for classroom accommodations and exam provisions",
      "Difficulty identifying whether issue is learning, attention, or motor-based",
    ],
    therapyRole: [
      "Assessment of visual-motor, fine motor, and sensory processing contributions to learning",
      "Brain Gym® activities targeting reading, writing, and processing pathways",
      "Handwriting Without Tears® intervention for written expression",
      "Visual-perceptual and visual-motor skill training",
      "Attention and executive function strategies for learning tasks",
      "School collaboration for accommodations and modified tasks",
      "Parent guidance on home learning environment setup",
      "Building confidence through success-based, graded activities",
    ],
    benefits: [
      "Improved reading readiness and visual tracking",
      "Clearer, faster handwriting and written expression",
      "Better attention during learning tasks",
      "Increased homework completion and reduced battles",
      "Classroom accommodations that level the playing field",
      "Child understands their learning profile and strengths",
      "Parents equipped to advocate effectively at school",
    ],
    whenToBegin: "If your child is struggling academically despite tutoring or extra help, an OT assessment can identify sensory-motor factors that tutoring alone cannot address. Early support in primary school prevents secondary emotional issues.",
    faqs: [
      { q: "Is OT the same as tutoring?", a: "No. Tutoring teaches content. OT addresses the sensory-motor and processing foundations that make learning possible." },
      { q: "Can OT help with dyslexia?", a: "OT addresses visual-motor, attention, and processing components that often co-occur with dyslexia, complementing specialized reading programs." },
      { q: "Does Dr. Sharuja Sarap diagnose learning disabilities?", a: "OT assessment identifies functional skill gaps. Formal learning disability diagnosis is made by educational psychologists or developmental pediatricians." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "handwriting-training"],
  },
  {
    slug: "motor-coordination-challenges",
    title: "Motor Coordination Challenges",
    metaDescription: "Motor coordination therapy for children in Mumbai. Dr. Sharuja Sarap improves balance, motor planning & physical confidence in Kandivali West.",
    keywords: ["motor coordination therapy Mumbai", "dyspraxia OT Kandivali", "coordination therapy children Mumbai"],
    intro: "Motor coordination challenges — sometimes called dyspraxia or developmental coordination disorder — affect a child's ability to plan, execute, and learn new physical movements. This impacts everything from playground participation to handwriting and self-care. At Thrive with sharuja, Dr. Sharuja Sarap uses targeted occupational therapy and aquatic therapy to help children in Mumbai build the motor planning, balance, and coordination skills for confident physical participation.",
    symptoms: [
      "Clumsiness — frequent tripping, bumping into objects",
      "Difficulty learning new physical skills — riding bike, swimming, sports",
      "Poor ball skills — catching, throwing, kicking",
      "Awkward or immature running and jumping patterns",
      "Difficulty with bilateral coordination — cutting, climbing, jumping jacks",
      "Slow or hesitant approach to physical activities",
      "Poor handwriting linked to motor planning difficulties",
      "Fatigue during physical tasks that peers manage easily",
    ],
    challenges: [
      "Avoidance of PE and playground activities",
      "Social exclusion from sports and physical games",
      "Low self-confidence about physical abilities",
      "Difficulty with self-care requiring coordination — buttons, shoelaces",
      "Academic impact through poor handwriting and tool use",
      "Parent concern about long-term physical development",
      "Risk of sedentary lifestyle and reduced fitness",
    ],
    therapyRole: [
      "Motor planning (praxis) assessment and intervention",
      "Balance and postural stability training",
      "Bilateral coordination activities through play",
      "Aquatic therapy for strength and coordination in reduced-gravity environment",
      "Fine motor coordination for tool use and handwriting",
      "Graded exposure to challenging physical tasks with success scaffolding",
      "Home exercise programs for daily practice",
      "School recommendations for PE participation and accommodations",
    ],
    benefits: [
      "Improved balance, coordination, and motor planning",
      "Greater willingness to attempt new physical activities",
      "Better playground and sports participation",
      "Improved handwriting and tool use",
      "Increased physical confidence and self-esteem",
      "Reduced clumsiness-related injuries and frustration",
      "Foundation for lifelong physical activity enjoyment",
    ],
    whenToBegin: "If your child avoids physical play, struggles with new motor tasks, or appears significantly clumsier than peers, an OT assessment can identify coordination challenges and begin targeted intervention.",
    faqs: [
      { q: "Is clumsiness always dyspraxia?", a: "Not always, but persistent coordination difficulties across multiple activities warrant professional assessment." },
      { q: "Can coordination improve with age?", a: "Some children improve naturally; many benefit significantly from targeted OT and aquatic therapy." },
      { q: "Does aquatic therapy help coordination?", a: "Yes. Water provides a safe, supportive environment for practicing balance and movement patterns." },
    ],
    relatedServices: ["occupational-therapy", "aquatic-therapy", "brain-gym"],
  },
  {
    slug: "handwriting-difficulties",
    title: "Handwriting Difficulties",
    metaDescription: "Handwriting therapy for children in Mumbai. Dr. Sharuja Sarap is HWT-certified, helping kids build legible writing & classroom confidence in Kandivali.",
    keywords: ["handwriting therapy Mumbai", "Handwriting Without Tears Kandivali", "handwriting OT Mumbai"],
    intro: "Handwriting is one of the most complex skills a child develops — requiring coordination of visual, motor, sensory, cognitive, and postural systems simultaneously. When handwriting is illegible, slow, or painful, it affects academic performance, self-esteem, and classroom participation. Dr. Sharuja Sarap at Thrive with sharuja is certified in Handwriting Without Tears® (HWT) and provides specialized handwriting training for children in Kandivali West and across Mumbai.",
    symptoms: [
      "Illegible letter formation or inconsistent sizing",
      "Poor pencil grip — too tight, too loose, or awkward hold",
      "Slow writing speed unable to keep up with classroom demands",
      "Hand fatigue or pain during or after writing",
      "Reversal of letters and numbers beyond age 7–8",
      "Avoidance of writing tasks and homework resistance",
      "Difficulty staying on lines or within margins",
      "Poor spacing between letters and words",
    ],
    challenges: [
      "Incomplete written assignments and exam papers",
      "Teacher frustration and reduced grades despite knowledge",
      "Child labeled as careless or lazy",
      "Avoidance of creative writing and journaling",
      "Difficulty with note-taking as academic demands increase",
      "Impact on exam performance under timed conditions",
      "Low self-confidence about academic abilities",
    ],
    therapyRole: [
      "Comprehensive handwriting and fine motor assessment",
      "Handwriting Without Tears® structured intervention program",
      "Pencil grip correction and adaptive tool recommendations",
      "Hand strength and dexterity building activities",
      "Postural stability training for sustained writing",
      "Visual-motor integration activities supporting letter formation",
      "School collaboration for accommodations and modified tasks",
      "Home practice programs with parent guidance",
    ],
    benefits: [
      "Legible, consistent handwriting for classroom and exams",
      "Improved writing speed and reduced hand fatigue",
      "Functional pencil grip that supports long-term writing",
      "Increased confidence in written work",
      "Classroom accommodations when needed",
      "Child re-engages with writing tasks willingly",
      "Teachers notice improvement in written output quality",
    ],
    whenToBegin: "If handwriting remains illegible or painfully slow by age 7–8, or if your child actively avoids writing, specialized handwriting training can address underlying motor and sensory factors that practice alone cannot fix.",
    faqs: [
      { q: "Will more writing practice at home fix the problem?", a: "Practice without addressing underlying grip, strength, and visual-motor issues often increases frustration. Targeted OT identifies and treats root causes." },
      { q: "Is HWT suitable for older children?", a: "Yes. HWT programs adapt to different age groups, including remediation for older students with persistent difficulties." },
      { q: "Can my child use a laptop instead?", a: "Typing is a valid accommodation, but OT addresses foundational skills that support both handwriting and keyboard use." },
    ],
    relatedServices: ["handwriting-training", "occupational-therapy", "brain-gym"],
  },
  {
    slug: "attention-difficulties",
    title: "Attention Difficulties",
    metaDescription: "Attention & focus therapy for children in Mumbai. Dr. Sharuja Sarap uses OT & Brain Gym in Kandivali to build learning readiness & sustained focus.",
    keywords: ["attention therapy children Mumbai", "focus therapy Kandivali", "learning readiness OT Mumbai"],
    intro: "Attention difficulties affect a child's ability to focus, filter distractions, and sustain effort on tasks — impacting learning, play, and social interactions. While often associated with ADHD, many children experience attention challenges without a formal diagnosis. At Thrive with sharuja, Dr. Sharuja Sarap uses occupational therapy and Brain Gym® movement strategies to help children in Kandivali West build the attention stamina and self-regulation skills for confident learning and participation.",
    symptoms: [
      "Difficulty sustaining focus beyond a few minutes",
      "Easily distracted by sounds, movement, or thoughts",
      "Difficulty following multi-step verbal instructions",
      "Daydreaming or appearing 'in their own world'",
      "Difficulty completing tasks without frequent redirection",
      "Restlessness during seated activities",
      "Difficulty with tasks requiring sustained visual attention",
      "Inconsistent performance — focused one day, scattered the next",
    ],
    challenges: [
      "Incomplete classroom work and homework",
      "Teacher reports of inattention despite intelligence",
      "Difficulty engaging in structured group activities",
      "Safety concerns due to inattention — crossing roads, following instructions",
      "Parent frustration with repeated reminders and redirection",
      "Risk of being overlooked in classroom due to quiet inattention",
      "Difficulty building on previous learning due to poor retention",
    ],
    therapyRole: [
      "Attention and sensory profile assessment",
      "Brain Gym® activities activating focus and learning readiness",
      "Sensory regulation strategies for optimal alertness",
      "Graded attention-building activities with increasing duration",
      "Environmental modification for home study and classroom",
      "Movement break protocols for sustained focus",
      "Parent coaching on attention-supportive routines",
      "School recommendations for seating, tasks, and breaks",
    ],
    benefits: [
      "Improved sustained attention during tasks",
      "Better task completion at home and school",
      "Practical strategies for managing distractions",
      "Increased learning readiness and academic engagement",
      "Child learns to recognize and manage their attention patterns",
      "Reduced parent redirection and homework battles",
      "Teachers equipped with classroom support strategies",
    ],
    whenToBegin: "If attention difficulties are affecting school performance or daily routines — whether or not ADHD has been diagnosed — OT can build foundational focus skills before academic gaps widen.",
    faqs: [
      { q: "Is this the same as ADHD therapy?", a: "Attention difficulties overlap significantly with ADHD, but OT also supports children with focus challenges who do not meet full ADHD criteria." },
      { q: "How quickly can attention improve?", a: "Many families notice changes within 4–8 weeks of consistent sessions and home practice." },
      { q: "Do you recommend reduced screen time?", a: "We guide families on balanced routines. Excessive unstructured screen time can impact attention and sleep, affecting therapy progress." },
    ],
    relatedServices: ["occupational-therapy", "brain-gym", "handwriting-training"],
  },
];

export const allConditionsContent = [...conditionsContent, ...additionalConditionsContent];

export function getConditionContent(slug: string) {
  return allConditionsContent.find((c) => c.slug === slug);
}
