export const aboutContent = {
  aboutMe: {
    title: "About Me",
    greeting: "Hello,",
    credentials: [
      "I am Dr. Sharuja",
      "Paediatric occupational therapist",
      "Aquatic therapist",
      "Brain gym instructor",
    ],
    paragraphs: [
      "I am an occupational therapist with over 18 years of experience supporting children with developmental, sensory, and neurological needs. My work focuses on helping children participate confidently in everyday activities at home, school, and in the community.",
      "I hold a Master's degree in occupational therapy with a specialization in pediatrics and am currently pursuing my PhD. My academic and clinical background allows me to combine evidence-based practice with practical, family-centered intervention.",
      "Over the years, I have received specialized training in areas such as Brain Gym® (Instructor), Aquatic Therapy, Reflex Integration, Sensory Integration, Handwriting Development, and Oral Motor intervention. These approaches allow me to support children across a wide range of developmental and functional needs.",
      "In addition to clinical practice, I actively participate in research, workshops, conferences, and academic lectures, sharing knowledge with parents, educators, and fellow professionals.",
      "My philosophy is simple: every child has a unique way of participating, belonging, and learning. My role is to help families discover and support that potential.",
    ],
  },
  inviteSharuja: {
    title: "Invite Sharuja",
    paragraphs: [
      "I am available to conduct sessions, workshops, and training programs for parents, educators, and professionals who work with children.",
      "These sessions are designed to bridge the gap between clinical research and real-life experiences, offering practical strategies that can be applied in everyday settings.",
    ],
  },
  availableFor: {
    title: "Available For",
    items: [
      "Parent Education Programs",
      "School Workshops",
      "Teacher Training Programs",
      "College & University Lectures",
      "Hospital Training Sessions",
      "Professional Development Programs",
      "Community Awareness Programs",
      "Conference Presentations",
    ],
  },
  expertise: {
    title: "Conditions We Support",
    items: [
      "Autism Spectrum Disorders",
      "ADHD",
      "Cerebral Palsy",
      "Developmental Delay",
      "Sensory Processing Difficulties",
      "Learning Difficulties",
      "Handwriting Difficulties",
      "Fine Motor Challenges",
      "Gross Motor Difficulties",
      "Feeding & Oral Motor Difficulties",
      "Primitive Reflex Retention",
      "Emotional Regulation Difficulties",
    ],
  },
  suitableFor: {
    title: "Suitable For",
    items: [
      "Schools",
      "Preschools",
      "Colleges",
      "Universities",
      "Hospitals",
      "Clinics",
      "NGOs",
      "Parent Groups",
      "Professional Organizations",
    ],
  },
} as const;
